In [1]:
# Numpy: Number + Python
# main object: ndarray

In [1]:
import numpy
numpy.array

In [2]:
import numpy as np

my_list = [10,20,30]
np.array(my_list)

array([10, 20, 30])

In [3]:
list_of_lists = [[1,2,3],[4,5,6],[7,8,9]]
np.array(list_of_lists)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [4]:
# ndarray.shape: gives the dimension of the array
# ndarray.dtype: an object describing the type of the elements in an array
# ndarray.reshape: returns an array containing the data with a new shape

In [5]:
my_list = [10,20,30]

arr = np.array(my_list)
print(arr.dtype)
print(arr.shape)

int64
(3,)

In [7]:
twod_array=np.array(list_of_lists)
print(twod_array.shape)

(3, 3)

In [10]:
# arange
np.arange(0,10)
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [11]:
# in this the type is float64 hence the 0.
np.zeros((2,3))
# if we want the type to be int64 we can:
# np.zeros((2,3), dtype=int)

array([[0., 0., 0.],
       [0., 0., 0.]])

In [12]:
np.ones((2,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [13]:
# linspace: return evenly spaced numbers over a specified interval
# linspace(start, stop, num=50, endpoint=True, retstep=False)
np.linspace(0,10,7)

array([ 0.        ,  1.66666667,  3.33333333,  5.        ,  6.66666667,
        8.33333333, 10.        ])

# Why pandas
1. Intrinsic Data Alignment
2. Data Standardization Functions
3. Data Operation Functions
4. Functions for handling missing data
5. Data Structures Handling Major Use Cases

# Features of Pandas:
1. Powerful Data Structure
2. Fast and Efficient Data Wrangling
3. Easy Data Aggregation and Transformation
4. Tools for reading/writing data
5. Intelligent and Automated Data Alignment
6. High Performance Merging and Joining of Data Sets

# Pandas Data Strucutres:
1. Series:
   * One-dimensional labeled array
   * Supports Multiple Data Types
2. Data Frame:
   * Two-dimensional labeled array
   * Supports Multiple Data Types
   * Input can be series
   * Input can be other data frame
3. Panel:
   * Three-dimensional labled array
   * Supports multiple data types
   * Item-> axis 0
   * Major axis -> rows
   * Minor axis -> columns
4. Panel 4D(experimental):
   * Four-dimensional labeled array
   * Supports multiple data types
   * Labels -> axis 0
   * Items -> axis 1
   * Major axis -> rows
   * Minor axis -> columns

# Pandas Series:

In [2]:
import pandas as pd

my_list = [10,20,30]
ser = pd.Series(my_list)

print(ser)
print(ser.index)
print(ser.values)

0    10
1    20
2    30
dtype: int64
RangeIndex(start=0, stop=3, step=1)
[10 20 30]

In [3]:
# Creating a series from numpy array
import numpy as np
import pandas as pd

index = ['a','b','c']
arr = np.array([10,20,30])

pd.Series(data=arr, index=index)

a    10
b    20
c    30
dtype: int64

In [4]:
# Creating a series from dictionary
import pandas as pd

d= {'a':10, 'b':20, 'c':30}
pd.Series(d)

a    10
b    20
c    30
dtype: int64

In [6]:
# Using index in series
import pandas as pd
ser1 = pd.Series(data=[1,2,3,4], index=['USA', 'UK', 'India', 'Japan'])
ser2 = pd.Series(data=[1,2,3,4], index=['USA', 'UK', 'Italy', 'Japan'])

print(ser1['USA'])

1

In [7]:
print(ser1+ser2)

India    NaN
Italy    NaN
Japan    8.0
UK       4.0
USA      2.0
dtype: float64

In [2]:
# Data Frames:
import pandas as pd
import numpy as np

df = pd.DataFrame([[1,2,3],
       [4,5,6],
       [7,8,9]])
df

   0  1  2
0  1  2  3
1  4  5  6
2  7  8  9

In [3]:
type(df)

pandas.core.frame.DataFrame

In [4]:
print(df.shape)
print(df.index)

(3, 3)
RangeIndex(start=0, stop=3, step=1)

In [5]:
df2 = pd.DataFrame([[1,2,3], [4,5,6], [7,8,9], [10,11,12]],
                  index=['a','b','c','d'], columns=['x','y','z'])
df2

    x   y   z
a   1   2   3
b   4   5   6
c   7   8   9
d  10  11  12

# Weather Dataset Project

In [7]:
weather_df = pd.read_csv('weather_2012.csv')

print('Shape: ', weather_df.shape)
print('Index: ', weather_df.index)

Shape:  (8784, 8)
Index:  RangeIndex(start=0, stop=8784, step=1)

In [8]:
weather_df['Date/Time'].head()

0    2012-01-01 00:00:00
1    2012-01-01 01:00:00
2    2012-01-01 02:00:00
3    2012-01-01 03:00:00
4    2012-01-01 04:00:00
Name: Date/Time, dtype: object

In [9]:
weather_df.head()

,Date/Time,Temp (C),Dew Point Temp (C),Rel Hum (%),Wind Spd (km/h),Visibility (km),Stn Press (kPa),Weather
0,2012-01-01 00:00:00,-1.8,-3.9,86,4,8.0,101.24,Fog
1,2012-01-01 01:00:00,-1.8,-3.7,87,4,8.0,101.24,Fog
2,2012-01-01 02:00:00,-1.8,-3.4,89,7,4.0,101.26,"Freezing Drizzle,Fog"
3,2012-01-01 03:00:00,-1.5,-3.2,88,6,4.0,101.27,"Freezing Drizzle,Fog"
4,2012-01-01 04:00:00,-1.5,-3.3,88,7,4.8,101.23,Fog

In [10]:
type(weather_df['Date/Time'])

pandas.core.series.Series

In [11]:
# Let's convert the Date/Time column datatype from object to timestamp so that we can access the month directly using dt.month
weather_df['Date/Time'] = pd.to_datetime(weather_df['Date/Time'])
weather_df['Date/Time'].head()

0   2012-01-01 00:00:00
1   2012-01-01 01:00:00
2   2012-01-01 02:00:00
3   2012-01-01 03:00:00
4   2012-01-01 04:00:00
Name: Date/Time, dtype: datetime64[ns]

In [12]:
# How to analyze data frames
# .info: Provides a summary of a DataFrame: rows, columns, data types of columns

weather_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8784 entries, 0 to 8783
Data columns (total 8 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Date/Time           8784 non-null   datetime64[ns]
 1   Temp (C)            8784 non-null   float64
 2   Dew Point Temp (C)  8784 non-null   float64
 3   Rel Hum (%)         8784 non-null   int64
 4   Wind Spd (km/h)     8784 non-null   int64
 5   Visibility (km)     8784 non-null   float64
 6   Stn Press (kPa)     8784 non-null   float64
 7   Weather             8784 non-null   object
dtypes: datetime64[ns](1), float64(4), int64(2), object(1)
memory usage: 549.1+ KB

In [14]:
# .head: returns first 5 also can give parameter
weather_df.head(10)

,Date/Time,Temp (C),Dew Point Temp (C),Rel Hum (%),Wind Spd (km/h),Visibility (km),Stn Press (kPa),Weather
0,2012-01-01 00:00:00,-1.8,-3.9,86,4,8.0,101.24,Fog
1,2012-01-01 01:00:00,-1.8,-3.7,87,4,8.0,101.24,Fog
2,2012-01-01 02:00:00,-1.8,-3.4,89,7,4.0,101.26,"Freezing Drizzle,Fog"
3,2012-01-01 03:00:00,-1.5,-3.2,88,6,4.0,101.27,"Freezing Drizzle,Fog"
4,2012-01-01 04:00:00,-1.5,-3.3,88,7,4.8,101.23,Fog
5,2012-01-01 05:00:00,-1.4,-3.3,87,9,6.4,101.27,Fog
6,2012-01-01 06:00:00,-1.5,-3.1,89,7,6.4,101.29,Fog
7,2012-01-01 07:00:00,-1.4,-3.6,85,7,8.0,101.26,Fog
8,2012-01-01 08:00:00,-1.4,-3.6,85,9,8.0,101.23,Fog
9,2012-01-01 09:00:00,-1.3,-3.1,88,15,4.0,101.20,Fog

In [16]:
# .tail: returns the last 5 also can give parameter
weather_df.tail()

,Date/Time,Temp (C),Dew Point Temp (C),Rel Hum (%),Wind Spd (km/h),Visibility (km),Stn Press (kPa),Weather
8779,2012-12-31 19:00:00,0.1,-2.7,81,30,9.7,100.13,Snow
8780,2012-12-31 20:00:00,0.2,-2.4,83,24,9.7,100.03,Snow
8781,2012-12-31 21:00:00,-0.5,-1.5,93,28,4.8,99.95,Snow
8782,2012-12-31 22:00:00,-0.2,-1.8,89,28,9.7,99.91,Snow
8783,2012-12-31 23:00:00,0.0,-2.1,86,30,11.3,99.89,Snow

In [17]:
weather_df.tail(10)

,Date/Time,Temp (C),Dew Point Temp (C),Rel Hum (%),Wind Spd (km/h),Visibility (km),Stn Press (kPa),Weather
8774,2012-12-31 14:00:00,-3.4,-5.7,84,6,11.3,100.57,Snow
8775,2012-12-31 15:00:00,-2.3,-4.6,84,9,9.7,100.47,Snow
8776,2012-12-31 16:00:00,-1.4,-4.0,82,13,12.9,100.40,Snow
8777,2012-12-31 17:00:00,-1.1,-3.3,85,19,9.7,100.30,Snow
8778,2012-12-31 18:00:00,-1.3,-3.1,88,17,9.7,100.19,Snow
8779,2012-12-31 19:00:00,0.1,-2.7,81,30,9.7,100.13,Snow
8780,2012-12-31 20:00:00,0.2,-2.4,83,24,9.7,100.03,Snow
8781,2012-12-31 21:00:00,-0.5,-1.5,93,28,4.8,99.95,Snow
8782,2012-12-31 22:00:00,-0.2,-1.8,89,28,9.7,99.91,Snow
8783,2012-12-31 23:00:00,0.0,-2.1,86,30,11.3,99.89,Snow

In [22]:
# .index: This attribute provides the index of the data frame
weather_df.index

RangeIndex(start=0, stop=8784, step=1)

In [24]:
# .unique: The name itself is self-sufficient
weather_df['Weather'].unique()

array(['Fog', 'Freezing Drizzle,Fog', 'Mostly Cloudy', 'Cloudy', 'Rain',
       'Rain Showers', 'Mainly Clear', 'Snow Showers', 'Snow', 'Clear',
       'Freezing Rain,Fog', 'Freezing Rain', 'Freezing Drizzle',
       'Rain,Snow', 'Moderate Snow', 'Freezing Drizzle,Snow',
       'Freezing Rain,Snow Grains', 'Snow,Blowing Snow', 'Freezing Fog',
       'Haze', 'Rain,Fog', 'Drizzle,Fog', 'Drizzle',
       'Freezing Drizzle,Haze', 'Freezing Rain,Haze', 'Snow,Haze',
       'Snow,Fog', 'Snow,Ice Pellets', 'Rain,Haze', 'Thunderstorms,Rain',
       'Thunderstorms,Rain Showers', 'Thunderstorms,Heavy Rain Showers',
       'Thunderstorms,Rain Showers,Fog', 'Thunderstorms',
       'Thunderstorms,Rain,Fog',
       'Thunderstorms,Moderate Rain Showers,Fog', 'Rain Showers,Fog',
       'Rain Showers,Snow Showers', 'Snow Pellets', 'Rain,Snow,Fog',
       'Moderate Rain,Fog', 'Freezing Rain,Ice Pellets,Fog',
       'Drizzle,Ice Pellets,Fog', 'Drizzle,Snow', 'Rain,Ice Pellets',
       'Drizzle,Snow,Fog', 'Rain,Snow Grains', 'Rain,Snow,Ice Pellets',
       'Snow Showers,Fog', 'Moderate Snow,Blowing Snow'], dtype=object)

In [25]:
# .nunique: The number of unique elements. ignores na values 
weather_df['Weather'].nunique()

50

In [26]:
# .value_counts: Understand from the example
weather_df['Weather'].value_counts()

Weather
Mainly Clear                               2106
Mostly Cloudy                              2069
Cloudy                                     1728
Clear                                      1326
Snow                                        390
Rain                                        306
Rain Showers                                188
Fog                                         150
Rain,Fog                                    116
Drizzle,Fog                                  80
Snow Showers                                 60
Drizzle                                      41
Snow,Fog                                     37
Snow,Blowing Snow                            19
Rain,Snow                                    18
Thunderstorms,Rain Showers                   16
Haze                                         16
Drizzle,Snow,Fog                             15
Freezing Rain                                14
Freezing Drizzle,Snow                        11
Freezing Drizzle                              7
Snow,Ice Pellets                              6
Freezing Drizzle,Fog                          6
Snow,Haze                                     5
Freezing Fog                                  4
Snow Showers,Fog                              4
Moderate Snow                                 4
Rain,Snow,Ice Pellets                         4
Freezing Rain,Fog                             4
Freezing Drizzle,Haze                         3
Rain,Haze                                     3
Thunderstorms,Rain                            3
Thunderstorms,Rain Showers,Fog                3
Freezing Rain,Haze                            2
Drizzle,Snow                                  2
Rain Showers,Snow Showers                     2
Thunderstorms                                 2
Moderate Snow,Blowing Snow                    2
Rain Showers,Fog                              1
Thunderstorms,Moderate Rain Showers,Fog       1
Snow Pellets                                  1
Rain,Snow,Fog                                 1
Moderate Rain,Fog                             1
Freezing Rain,Ice Pellets,Fog                 1
Drizzle,Ice Pellets,Fog                       1
Thunderstorms,Rain,Fog                        1
Rain,Ice Pellets                              1
Rain,Snow Grains                              1
Thunderstorms,Heavy Rain Showers              1
Freezing Rain,Snow Grains                     1
Name: count, dtype: int64

In [29]:
weather_df['Weather'].value_counts()[2]

/var/folders/8t/fh2nryhx7hvfc36kndxf3gw40000gn/T/ipykernel_62554/728081491.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  weather_df['Weather'].value_counts()[2]

1728

In [30]:
weather_df['Weather'].value_counts()['Rain']

306

# Data Manipulation/Transformation

## Selection(Part 1)

In [32]:
col = weather_df['Weather']
print(type(col))
col.head()

<class 'pandas.core.series.Series'>

0                     Fog
1                     Fog
2    Freezing Drizzle,Fog
3    Freezing Drizzle,Fog
4                     Fog
Name: Weather, dtype: object

In [34]:
two_cols = weather_df[['Weather','Temp (C)']]

print(type(two_cols))
two_cols.head()

<class 'pandas.core.frame.DataFrame'>

                Weather  Temp (C)
0                   Fog      -1.8
1                   Fog      -1.8
2  Freezing Drizzle,Fog      -1.8
3  Freezing Drizzle,Fog      -1.5
4                   Fog      -1.5

In [37]:
# When working with Pandas always try to ignore slicing instead use .loc and .iloc
weather_df.loc[0:5, ['Visibility (km)', 'Rel Hum (%)']]

   Visibility (km)  Rel Hum (%)
0              8.0           86
1              8.0           87
2              4.0           89
3              4.0           88
4              4.8           88
5              6.4           87

In [38]:
weather_df[['Visibility (km)', 'Rel Hum (%)']].loc[0:5]

   Visibility (km)  Rel Hum (%)
0              8.0           86
1              8.0           87
2              4.0           89
3              4.0           88
4              4.8           88
5              6.4           87

In [39]:
weather_df[['Visibility (km)', 'Rel Hum (%)']].iloc[0:5]

   Visibility (km)  Rel Hum (%)
0              8.0           86
1              8.0           87
2              4.0           89
3              4.0           88
4              4.8           88

# Filtering

In [40]:
weather_df['Weather'].unique()

array(['Fog', 'Freezing Drizzle,Fog', 'Mostly Cloudy', 'Cloudy', 'Rain',
       'Rain Showers', 'Mainly Clear', 'Snow Showers', 'Snow', 'Clear',
       'Freezing Rain,Fog', 'Freezing Rain', 'Freezing Drizzle',
       'Rain,Snow', 'Moderate Snow', 'Freezing Drizzle,Snow',
       'Freezing Rain,Snow Grains', 'Snow,Blowing Snow', 'Freezing Fog',
       'Haze', 'Rain,Fog', 'Drizzle,Fog', 'Drizzle',
       'Freezing Drizzle,Haze', 'Freezing Rain,Haze', 'Snow,Haze',
       'Snow,Fog', 'Snow,Ice Pellets', 'Rain,Haze', 'Thunderstorms,Rain',
       'Thunderstorms,Rain Showers', 'Thunderstorms,Heavy Rain Showers',
       'Thunderstorms,Rain Showers,Fog', 'Thunderstorms',
       'Thunderstorms,Rain,Fog',
       'Thunderstorms,Moderate Rain Showers,Fog', 'Rain Showers,Fog',
       'Rain Showers,Snow Showers', 'Snow Pellets', 'Rain,Snow,Fog',
       'Moderate Rain,Fog', 'Freezing Rain,Ice Pellets,Fog',
       'Drizzle,Ice Pellets,Fog', 'Drizzle,Snow', 'Rain,Ice Pellets',
       'Drizzle,Snow,Fog', 'Rain,Snow Grains', 'Rain,Snow,Ice Pellets',
       'Snow Showers,Fog', 'Moderate Snow,Blowing Snow'], dtype=object)

In [41]:
snowed_filter = weather_df['Weather'].str.lower().str.contains('snow')
weather_df[snowed_filter]

,Date/Time,Temp (C),Dew Point Temp (C),Rel Hum (%),Wind Spd (km/h),Visibility (km),Stn Press (kPa),Weather
41,2012-01-02 17:00:00,-2.1,-9.5,57,22,25.0,99.66,Snow Showers
44,2012-01-02 20:00:00,-5.6,-13.4,54,24,25.0,100.07,Snow Showers
45,2012-01-02 21:00:00,-5.8,-12.8,58,26,25.0,100.15,Snow Showers
47,2012-01-02 23:00:00,-7.4,-14.1,59,17,19.3,100.27,Snow Showers
48,2012-01-03 00:00:00,-9.0,-16.0,57,28,25.0,100.35,Snow Showers
...,...,...,...,...,...,...,...,...
8779,2012-12-31 19:00:00,0.1,-2.7,81,30,9.7,100.13,Snow
8780,2012-12-31 20:00:00,0.2,-2.4,83,24,9.7,100.03,Snow
8781,2012-12-31 21:00:00,-0.5,-1.5,93,28,4.8,99.95,Snow
8782,2012-12-31 22:00:00,-0.2,-1.8,89,28,9.7,99.91,Snow
8783,2012-12-31 23:00:00,0.0,-2.1,86,30,11.3,99.89,Snow

In [42]:
weather_df['Weather'].iloc[8782]

'Snow'

In [43]:
speed_filter = (weather_df['Wind Spd (km/h)'] > 24) & (weather_df['Visibility (km)'] == 25)
weather_df[speed_filter]

,Date/Time,Temp (C),Dew Point Temp (C),Rel Hum (%),Wind Spd (km/h),Visibility (km),Stn Press (kPa),Weather
23,2012-01-01 23:00:00,5.3,2.0,79,30,25.0,99.31,Cloudy
24,2012-01-02 00:00:00,5.2,1.5,77,35,25.0,99.26,Rain Showers
25,2012-01-02 01:00:00,4.6,0.0,72,39,25.0,99.26,Cloudy
26,2012-01-02 02:00:00,3.9,-0.9,71,32,25.0,99.26,Mostly Cloudy
27,2012-01-02 03:00:00,3.7,-1.5,69,33,25.0,99.30,Mostly Cloudy
...,...,...,...,...,...,...,...,...
8705,2012-12-28 17:00:00,-8.6,-12.0,76,26,25.0,101.34,Mainly Clear
8753,2012-12-30 17:00:00,-12.1,-15.8,74,28,25.0,101.26,Mainly Clear
8755,2012-12-30 19:00:00,-13.4,-16.5,77,26,25.0,101.47,Mainly Clear
8759,2012-12-30 23:00:00,-12.1,-15.1,78,28,25.0,101.52,Mostly Cloudy
8760,2012-12-31 00:00:00,-11.1,-14.4,77,26,25.0,101.51,Cloudy

# Series Operations

In [46]:
weather_df['Wind Spd (km/h)'].head()

0    4
1    4
2    7
3    6
4    7
Name: Wind Spd (km/h), dtype: int64

In [45]:
weather_df['Wind Spd (km/h)'].head() + 10

0    14
1    14
2    17
3    16
4    17
Name: Wind Spd (km/h), dtype: int64

In [48]:
weather_df.head()

,Date/Time,Temp (C),Dew Point Temp (C),Rel Hum (%),Wind Spd (km/h),Visibility (km),Stn Press (kPa),Weather
0,2012-01-01 00:00:00,-1.8,-3.9,86,4,8.0,101.24,Fog
1,2012-01-01 01:00:00,-1.8,-3.7,87,4,8.0,101.24,Fog
2,2012-01-01 02:00:00,-1.8,-3.4,89,7,4.0,101.26,"Freezing Drizzle,Fog"
3,2012-01-01 03:00:00,-1.5,-3.2,88,6,4.0,101.27,"Freezing Drizzle,Fog"
4,2012-01-01 04:00:00,-1.5,-3.3,88,7,4.8,101.23,Fog

In [49]:
weather_df['new_temp_col'] = weather_df['Temp (C)'] + weather_df['Dew Point Temp (C)']
weather_df.head()

,Date/Time,Temp (C),Dew Point Temp (C),Rel Hum (%),Wind Spd (km/h),Visibility (km),Stn Press (kPa),Weather,new_temp_col
0,2012-01-01 00:00:00,-1.8,-3.9,86,4,8.0,101.24,Fog,-5.7
1,2012-01-01 01:00:00,-1.8,-3.7,87,4,8.0,101.24,Fog,-5.5
2,2012-01-01 02:00:00,-1.8,-3.4,89,7,4.0,101.26,"Freezing Drizzle,Fog",-5.2
3,2012-01-01 03:00:00,-1.5,-3.2,88,6,4.0,101.27,"Freezing Drizzle,Fog",-4.7
4,2012-01-01 04:00:00,-1.5,-3.3,88,7,4.8,101.23,Fog,-4.8

In [50]:
# .apply : understand from the example

def times2(value):
    return value * 2

t2 = weather_df['Visibility (km)'].apply(times2)
t2.head()

0    16.0
1    16.0
2     8.0
3     8.0
4     9.6
Name: Visibility (km), dtype: float64

In [51]:
weather_df['Visibility (km)'].describe()

count    8784.000000
mean       27.664447
std        12.622688
min         0.200000
25%        24.100000
50%        25.000000
75%        25.000000
max        48.300000
Name: Visibility (km), dtype: float64

In [63]:
# Adding/Updating columns
visibility_in_meter = weather_df['Visibility (km)'] * 1000
weather_df['Visibility (m)'] = visibility_in_meter

weather_df.head()

,Date/Time,Temp (C),Dew Point Temp (C),Rel Hum (%),Wind Spd (km/h),Visibility (km),Stn Press (kPa),Weather,new_temp_col,Visibility (m)
0,2012-01-01 00:00:00,-1.8,-3.9,86,4,8.0,101.24,Fog,-5.7,8000.0
1,2012-01-01 01:00:00,-1.8,-3.7,87,4,8.0,101.24,Fog,-5.5,8000.0
2,2012-01-01 02:00:00,-1.8,-3.4,89,7,4.0,101.26,"Freezing Drizzle,Fog",-5.2,4000.0
3,2012-01-01 03:00:00,-1.5,-3.2,88,6,4.0,101.27,"Freezing Drizzle,Fog",-4.7,4000.0
4,2012-01-01 04:00:00,-1.5,-3.3,88,7,4.8,101.23,Fog,-4.8,4800.0

In [64]:
weather_df.rename(columns={'Visibility (m)':'Visibility (meters)',
                          'Visibility (km)':'Visibility (kilometers)'}, inplace = True)
weather_df.head()

,Date/Time,Temp (C),Dew Point Temp (C),Rel Hum (%),Wind Spd (km/h),Visibility (kilometers),Stn Press (kPa),Weather,new_temp_col,Visibility (meters)
0,2012-01-01 00:00:00,-1.8,-3.9,86,4,8.0,101.24,Fog,-5.7,8000.0
1,2012-01-01 01:00:00,-1.8,-3.7,87,4,8.0,101.24,Fog,-5.5,8000.0
2,2012-01-01 02:00:00,-1.8,-3.4,89,7,4.0,101.26,"Freezing Drizzle,Fog",-5.2,4000.0
3,2012-01-01 03:00:00,-1.5,-3.2,88,6,4.0,101.27,"Freezing Drizzle,Fog",-4.7,4000.0
4,2012-01-01 04:00:00,-1.5,-3.3,88,7,4.8,101.23,Fog,-4.8,4800.0

In [65]:
weather_df.rename(columns={'Visibility (kilometers)':'Visibility (km)'}, inplace=True)
weather_df.head()

,Date/Time,Temp (C),Dew Point Temp (C),Rel Hum (%),Wind Spd (km/h),Visibility (km),Stn Press (kPa),Weather,new_temp_col,Visibility (meters)
0,2012-01-01 00:00:00,-1.8,-3.9,86,4,8.0,101.24,Fog,-5.7,8000.0
1,2012-01-01 01:00:00,-1.8,-3.7,87,4,8.0,101.24,Fog,-5.5,8000.0
2,2012-01-01 02:00:00,-1.8,-3.4,89,7,4.0,101.26,"Freezing Drizzle,Fog",-5.2,4000.0
3,2012-01-01 03:00:00,-1.5,-3.2,88,6,4.0,101.27,"Freezing Drizzle,Fog",-4.7,4000.0
4,2012-01-01 04:00:00,-1.5,-3.3,88,7,4.8,101.23,Fog,-4.8,4800.0

In [66]:
weather_df.drop(labels = ['Visibility (meters)'], axis=1)
weather_df.head()

,Date/Time,Temp (C),Dew Point Temp (C),Rel Hum (%),Wind Spd (km/h),Visibility (km),Stn Press (kPa),Weather,new_temp_col,Visibility (meters)
0,2012-01-01 00:00:00,-1.8,-3.9,86,4,8.0,101.24,Fog,-5.7,8000.0
1,2012-01-01 01:00:00,-1.8,-3.7,87,4,8.0,101.24,Fog,-5.5,8000.0
2,2012-01-01 02:00:00,-1.8,-3.4,89,7,4.0,101.26,"Freezing Drizzle,Fog",-5.2,4000.0
3,2012-01-01 03:00:00,-1.5,-3.2,88,6,4.0,101.27,"Freezing Drizzle,Fog",-4.7,4000.0
4,2012-01-01 04:00:00,-1.5,-3.3,88,7,4.8,101.23,Fog,-4.8,4800.0

In [67]:
# Sorting
sorted_by_temp = weather_df.sort_values('Temp (C)', ascending=False)
sorted_by_temp.head()

,Date/Time,Temp (C),Dew Point Temp (C),Rel Hum (%),Wind Spd (km/h),Visibility (km),Stn Press (kPa),Weather,new_temp_col,Visibility (meters)
4695,2012-07-14 15:00:00,33.0,16.8,38,22,48.3,101.31,Mainly Clear,49.8,48300.0
4143,2012-06-21 15:00:00,33.0,19.0,44,24,24.1,100.20,Mainly Clear,52.0,24100.0
4696,2012-07-14 16:00:00,32.9,15.3,35,24,48.3,101.26,Mainly Clear,48.2,48300.0
5199,2012-08-04 15:00:00,32.8,18.8,44,17,24.1,101.39,Clear,51.6,24100.0
4694,2012-07-14 14:00:00,32.7,15.3,35,28,48.3,101.35,Mainly Clear,48.0,48300.0

In [68]:
weather_df = weather_df.drop(['Visibility (meters)'], axis = 1)
weather_df.head()

,Date/Time,Temp (C),Dew Point Temp (C),Rel Hum (%),Wind Spd (km/h),Visibility (km),Stn Press (kPa),Weather,new_temp_col
0,2012-01-01 00:00:00,-1.8,-3.9,86,4,8.0,101.24,Fog,-5.7
1,2012-01-01 01:00:00,-1.8,-3.7,87,4,8.0,101.24,Fog,-5.5
2,2012-01-01 02:00:00,-1.8,-3.4,89,7,4.0,101.26,"Freezing Drizzle,Fog",-5.2
3,2012-01-01 03:00:00,-1.5,-3.2,88,6,4.0,101.27,"Freezing Drizzle,Fog",-4.7
4,2012-01-01 04:00:00,-1.5,-3.3,88,7,4.8,101.23,Fog,-4.8

In [69]:
# Which were the top 10 hottest values and their count
sorted_value_count = weather_df['Temp (C)'].value_counts().sort_values(ascending = False)
sorted_value_count.iloc[:10]

Temp (C)
16.6    65
1.1     58
0.8     47
1.5     45
19.3    44
21.1    43
2.6     43
0.4     41
1.3     40
14.6    39
Name: count, dtype: int64

# Pivot Tables: Excellent way to Summarize your Data

* A pivot table is a tool that allows you to reorganize and summarize selected columns and rows of data in a dataframe
* Pivot tables provides and easy way to subset by one column and then apply a calculation like a sum or a mean
* Pivot tables first groups and then only applies a calculation

In [72]:
data = {
    'A': ['foo', 'foo', 'foo', 'bar', 'bar', 'bar'],
    'B': ['one', 'one', 'two', 'two', 'one', 'one'],
    'C': ['x', 'y', 'x', 'y', 'x', 'y'],
    'D': [1,3,2,5,4,1]
}

df = pd.DataFrame(data)
df

     A    B  C  D
0  foo  one  x  1
1  foo  one  y  3
2  foo  two  x  2
3  bar  two  y  5
4  bar  one  x  4
5  bar  one  y  1

In [78]:
pivot_df = df.pivot_table(
                values='D',    # We want to aggregate the values of which column
                index='A',     # We want to use which column as the new index
                columns=['C'],  # We want to use the values of which column as the new columns (optional)
                aggfunc='sum')# What aggregation function to use

pivot_df

C    x  y
A
bar  4  6
foo  3  3

In [80]:
pivot_df.reset_index()

C    A  x  y
0  bar  4  6
1  foo  3  3

In [81]:
weather_df['Date/Time'].dt.month

0        1
1        1
2        1
3        1
4        1
        ..
8779    12
8780    12
8781    12
8782    12
8783    12
Name: Date/Time, Length: 8784, dtype: int32

In [86]:
# groupby
mean_temperature_df = weather_df.groupby(weather_df['Date/Time'].dt.month).mean(numeric_only=True)
mean_temperature_df

,Temp (C),Dew Point Temp (C),Rel Hum (%),Wind Spd (km/h),Visibility (km),Stn Press (kPa),new_temp_col
Date/Time,,,,,,,
1,-7.371505,-12.294758,68.383065,18.108871,22.100269,101.005349,-19.666263
2,-4.225000,-9.221695,68.956897,14.837644,25.182184,101.142414,-13.446695
3,3.121237,-3.488575,64.862903,14.514785,26.177957,101.335255,-0.367339
4,7.009306,-1.934583,56.150000,17.369444,31.777083,100.716833,5.074722
5,16.237769,8.080780,61.760753,12.846774,29.418548,101.057164,24.318548
6,20.134028,11.738056,60.643056,14.681944,32.104167,100.784222,31.872083
7,22.790054,14.595430,62.017473,11.887097,33.655108,100.828333,37.385484
8,22.279301,15.644758,67.943548,13.931452,30.192608,100.927097,37.924059
9,16.484444,10.757917,71.165278,14.108333,30.603472,101.087903,27.242361
10,10.954973,6.533468,75.731183,15.475806,25.111022,100.909368,17.488441
11,0.931389,-4.179306,69.984722,13.973611,26.077083,101.658306,-3.247917
12,-3.306317,-6.129032,81.299731,17.614247,19.733199,101.174409,-9.435349

In [87]:
# Concat, Merge and Join do from video

# Working with datetime in Pandas DataFrame
-------------------------------------------

## 1) Convert strings to datetime

In [92]:
import pandas as pd
import numpy as np

df = pd.DataFrame({
    'date':['3/10/2000','3/11/2000', '3/12/2000'],
    'value':[2,3,4]
})

df

        date  value
0  3/10/2000      2
1  3/11/2000      3
2  3/12/2000      4

In [93]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    3 non-null      object
 1   value   3 non-null      int64
dtypes: int64(1), object(1)
memory usage: 180.0+ bytes

In [94]:
df['date']=pd.to_datetime(df['date'])

In [95]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    3 non-null      datetime64[ns]
 1   value   3 non-null      int64
dtypes: datetime64[ns](1), int64(1)
memory usage: 180.0 bytes

In [96]:
df

        date  value
0 2000-03-10      2
1 2000-03-11      3
2 2000-03-12      4

In [98]:
# Day first
df = pd.DataFrame({
    'date':['3/10/2000','3/11/2000', '3/12/2000'],
    'value':[2,3,4]
})
df['date']=pd.to_datetime(df['date'], dayfirst=True)
df

        date  value
0 2000-10-03      2
1 2000-11-03      3
2 2000-12-03      4

In [101]:
# Custom Format
df = pd.DataFrame({
    'date': ['2016-6-10 20:30:0',
             '2016-7-1 19:45:30',
             '2013-10-12 4:5:1'],
    'value': [2,3,4]
})

In [102]:
df

                date  value
0  2016-6-10 20:30:0      2
1  2016-7-1 19:45:30      3
2   2013-10-12 4:5:1      4

In [104]:
df['date'] = pd.to_datetime(df['date'], format='%Y-%d-%m %H:%M:%S')

In [105]:
df

                 date  value
0 2016-10-06 20:30:00      2
1 2016-01-07 19:45:30      3
2 2013-12-10 04:05:01      4

In [2]:
import pandas as pd
df = pd.DataFrame({
    'date':['3/10/2000','a/11/2000','3/12/2000'],
    'value':[2,3,4]
})
df

        date  value
0  3/10/2000      2
1  a/11/2000      3
2  3/12/2000      4

In [3]:
df['date'] = pd.to_datetime(df['date'])

ValueError: time data "a/11/2000" doesn't match format "%m/%d/%Y", at position 1. You might want to try:
    - passing `format` if your strings have a consistent format;
    - passing `format='ISO8601'` if your strings are all ISO8601 but not necessarily in exactly the same format;
    - passing `format='mixed'`, and the format will be inferred for each element individually. You might want to use `dayfirst` alongside this.

In [5]:
df['date'] = pd.to_datetime(df['date'], errors='ignore')

/var/folders/8t/fh2nryhx7hvfc36kndxf3gw40000gn/T/ipykernel_70406/3026744589.py:1: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  df['date'] = pd.to_datetime(df['date'], errors='ignore')

In [6]:
df

        date  value
0  3/10/2000      2
1  a/11/2000      3
2  3/12/2000      4

In [7]:
df['date'] = pd.to_datetime(df['date'], errors='coerce')
df

        date  value
0 2000-03-10      2
1        NaT      3
2 2000-03-12      4

## 2) Assemble a datetime from multiple columns

In [8]:
df = pd.DataFrame({
    'year':[2015,2016],
    'month':[2,3],
    'day':[4,5]
})
df

   year  month  day
0  2015      2    4
1  2016      3    5

In [ ]:
df['date']=pd.to_datetime(df)

In [11]:
df

   year  month  day       date
0  2015      2    4 2015-02-04
1  2016      3    5 2016-03-05

## 3) Get year, month and day

In [12]:
df = pd.DataFrame({
    'name': ['Tom', 'Andy', 'Lucas'],
    'DoB': ['08-05-1997','04-28-1996','12-16-1995']
})
df

    name         DoB
0    Tom  08-05-1997
1   Andy  04-28-1996
2  Lucas  12-16-1995

In [13]:
df['DoB']=pd.to_datetime(df['DoB'])
df

    name        DoB
0    Tom 1997-08-05
1   Andy 1996-04-28
2  Lucas 1995-12-16

In [14]:
df['year'] = df['DoB'].dt.year
df['month'] = df['DoB'].dt.month
df['day'] = df['DoB'].dt.day
df

    name        DoB  year  month  day
0    Tom 1997-08-05  1997      8    5
1   Andy 1996-04-28  1996      4   28
2  Lucas 1995-12-16  1995     12   16

## 4) Get the week of the year, the day of the week and leap year

In [17]:
df['week_of_year'] = df['DoB'].dt.isocalendar().week
df['day_of_week'] = df['DoB'].dt.dayofweek
df['is_leap_year']=df['DoB'].dt.is_leap_year
df

    name        DoB  year  month  day  week_of_year  day_of_week  is_leap_year
0    Tom 1997-08-05  1997      8    5            32            1         False
1   Andy 1996-04-28  1996      4   28            17            6          True
2  Lucas 1995-12-16  1995     12   16            50            5         False

In [19]:
dw_mapping = {
    0: 'Monday',
    1: 'Tuesday',
    2: 'Wednesday',
    3: 'Thursday',
    4: 'Friday',
    5: 'Saturday',
    6: 'Sunday'
}

df['day_of_week_name'] = df['DoB'].dt.weekday.map(dw_mapping)
df

,name,DoB,year,month,day,week_of_year,day_of_week,is_leap_year,day_of_week_name
0,Tom,1997-08-05,1997,8,5,32,1,False,Tuesday
1,Andy,1996-04-28,1996,4,28,17,6,True,Sunday
2,Lucas,1995-12-16,1995,12,16,50,5,False,Saturday

## 5) Get the age from date of birth

In [20]:
today = pd.to_datetime('today')
df['age'] = today.year - df['DoB'].dt.year

df

,name,DoB,year,month,day,week_of_year,day_of_week,is_leap_year,day_of_week_name,age
0,Tom,1997-08-05,1997,8,5,32,1,False,Tuesday,29
1,Andy,1996-04-28,1996,4,28,17,6,True,Sunday,30
2,Lucas,1995-12-16,1995,12,16,50,5,False,Saturday,31

## 6) Improve performance by setting date column as the index

In [21]:
df = pd.read_csv('city_sales.csv', parse_dates=['date'] )
df

                      date  num    city
0      2015-01-01 09:00:00    4  London
1      2015-01-01 09:01:00    4  London
2      2015-01-01 09:02:00    3  London
3      2015-01-01 09:03:00    3  London
4      2015-01-01 09:04:00    3  London
...                    ...  ...     ...
376428 2018-06-06 09:54:00    3  London
376429 2018-06-06 09:55:00    3  London
376430 2018-06-06 09:56:00    3  London
376431 2018-06-06 09:57:00    3  London
376432 2018-06-06 09:58:00    1  London

[376433 rows x 3 columns]

In [22]:
df = df.set_index(['date'])
df

                     num    city
date
2015-01-01 09:00:00    4  London
2015-01-01 09:01:00    4  London
2015-01-01 09:02:00    3  London
2015-01-01 09:03:00    3  London
2015-01-01 09:04:00    3  London
...                  ...     ...
2018-06-06 09:54:00    3  London
2018-06-06 09:55:00    3  London
2018-06-06 09:56:00    3  London
2018-06-06 09:57:00    3  London
2018-06-06 09:58:00    1  London

[376433 rows x 2 columns]

## 7) Select data with a specific year and perform aggregation

In [23]:
df.loc['2018']

                     num    city
date
2018-01-01 09:00:00    2  London
2018-01-01 09:01:00    1  London
2018-01-01 09:02:00    3  London
2018-01-01 09:03:00    3  London
2018-01-01 09:04:00    3  London
...                  ...     ...
2018-06-06 09:54:00    3  London
2018-06-06 09:55:00    3  London
2018-06-06 09:56:00    3  London
2018-06-06 09:57:00    3  London
2018-06-06 09:58:00    1  London

[47211 rows x 2 columns]

In [24]:
df.loc['2018','num'].sum()

132127