In [1]:
!pip install spotipy python_dotenv pandas

Requirement already satisfied: spotipy in /opt/anaconda3/lib/python3.14/site-packages (2.26.0)
Requirement already satisfied: python_dotenv in /opt/anaconda3/lib/python3.14/site-packages (1.2.1)
Requirement already satisfied: pandas in /opt/anaconda3/lib/python3.14/site-packages (3.0.3)
Requirement already satisfied: redis>=3.5.3 in /opt/anaconda3/lib/python3.14/site-packages (from spotipy) (8.1.0)
Requirement already satisfied: requests>=2.25.0 in /opt/anaconda3/lib/python3.14/site-packages (from spotipy) (2.34.2)
Requirement already satisfied: urllib3>=1.26.0 in /opt/anaconda3/lib/python3.14/site-packages (from spotipy) (2.7.0)
Requirement already satisfied: numpy>=2.3.3 in /opt/anaconda3/lib/python3.14/site-packages (from pandas) (2.4.6)
Requirement already satisfied: python-dateutil>=2.8.2 in /opt/anaconda3/lib/python3.14/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /opt/anaconda3/lib/python3.14/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /opt/anaconda3/lib/python3.14/site-packages (from requests>=2.25.0->spotipy) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in /opt/anaconda3/lib/python3.14/site-packages (from requests>=2.25.0->spotipy) (3.18)
Requirement already satisfied: certifi>=2023.5.7 in /opt/anaconda3/lib/python3.14/site-packages (from requests>=2.25.0->spotipy) (2026.6.17)

In [2]:
import spotipy
from spotipy import Spotify
from spotipy.oauth2 import SpotifyOAuth
from dotenv import load_dotenv
import os

load_dotenv()
CLIENT_ID = os.getenv("SPOTIFY_CLIENT_ID")
CLIENT_SECRET = os.getenv("SPOTIFY_CLIENT_SECRET")
REDIRECT_URI = os.getenv("SPOTIFY_REDIRECT_URI")

In [3]:
sp = Spotify(
    auth_manager=SpotifyOAuth(
        client_id=CLIENT_ID,
        client_secret=CLIENT_SECRET,
        redirect_uri=REDIRECT_URI,
        scope='playlist-read-private playlist-read-collaborative',
        open_browser=True
    )
)

In [4]:
playlist_link = 'https://open.spotify.com/playlist/1npQQ8nEAzp256gIK6Mf1d'
playlist_URI = playlist_link.split('/')[-1]

In [5]:
data = sp.playlist_tracks(playlist_URI)

In [6]:
data['items'][0]['item']['album']['id']

'2eeufspLkAubwTJfOGSrI8'

In [7]:
data['items'][1]['item']['album']['name']

'Believe'

In [8]:
data['items'][0]['item']['album']['artists'][0]['name']

'Shakira'

In [9]:
data['items'][0]['item']['album']['release_date']

'2026-05-14'

In [10]:
data['items'][0]['item']['album']['total_tracks']

1

In [11]:
album_list = []

for item in data['items']:
    row = item['item']['album']

    album_id = row['id']
    album_name = row['name']
    album_release_date = row['release_date']
    album_total_tracks = row['total_tracks']
    album_url = row['external_urls']['spotify']
    album_artists = ", ".join(artist["name"] for artist in row["artists"])

    album_element = {
        'album_id': album_id,
        'name': album_name,
        'release_date': album_release_date,
        'total_tracks': album_total_tracks,
        'url': album_url,
        'artist_name':album_artists
    }

    album_list.append(album_element)

album_list

[{'album_id': '2eeufspLkAubwTJfOGSrI8',
  'name': 'Dai Dai',
  'release_date': '2026-05-14',
  'total_tracks': 1,
  'url': 'https://open.spotify.com/album/2eeufspLkAubwTJfOGSrI8',
  'artist_name': 'Shakira, Burna Boy'},
 {'album_id': '5cxMa6oLINJzmZ8lF7wWQN',
  'name': 'Believe',
  'release_date': '2012-01-01',
  'total_tracks': 13,
  'url': 'https://open.spotify.com/album/5cxMa6oLINJzmZ8lF7wWQN',
  'artist_name': 'Justin Bieber'},
 {'album_id': '1x159B5VzbDWAGBik5cr1z',
  'name': 'hate that i made you love me',
  'release_date': '2026-05-29',
  'total_tracks': 1,
  'url': 'https://open.spotify.com/album/1x159B5VzbDWAGBik5cr1z',
  'artist_name': 'Ariana Grande'},
 {'album_id': '3ukkRHDHbN8tNRPKsGZR1h',
  'name': 'ARIRANG',
  'release_date': '2026-03-20',
  'total_tracks': 14,
  'url': 'https://open.spotify.com/album/3ukkRHDHbN8tNRPKsGZR1h',
  'artist_name': 'BTS'},
 {'album_id': '2jX6yKrWw9bY7JAYHhhtqZ',
  'name': 'Sweet Boy',
  'release_date': '2024-04-05',
  'total_tracks': 16,
  'url': 'https://open.spotify.com/album/2jX6yKrWw9bY7JAYHhhtqZ',
  'artist_name': 'Malcolm Todd'},
 {'album_id': '2ANVost0y2y52ema1E9xAZ',
  'name': 'Thriller',
  'release_date': '1982-11-30',
  'total_tracks': 9,
  'url': 'https://open.spotify.com/album/2ANVost0y2y52ema1E9xAZ',
  'artist_name': 'Michael Jackson'},
 {'album_id': '3ybCwWDhYDt2GYSCYFiF83',
  'name': 'Animal',
  'release_date': '2026-07-24',
  'total_tracks': 2,
  'url': 'https://open.spotify.com/album/3ybCwWDhYDt2GYSCYFiF83',
  'artist_name': 'KATSEYE'},
 {'album_id': '05jbNkYoEQdjVDHEHtg1gY',
  'name': "Don't Forget About Me, Demos",
  'release_date': '2018-10-16',
  'total_tracks': 8,
  'url': 'https://open.spotify.com/album/05jbNkYoEQdjVDHEHtg1gY',
  'artist_name': 'Dominic Fike'},
 {'album_id': '7Cdqksm4yTfiq0EfKPa86M',
  'name': 'Self Aware',
  'release_date': '2026-02-15',
  'total_tracks': 1,
  'url': 'https://open.spotify.com/album/7Cdqksm4yTfiq0EfKPa86M',
  'artist_name': 'Temper City'},
 {'album_id': '1VW1MFNstaJuygaoTPkdCk',
  'name': "(What's The Story) Morning Glory? [Remastered]",
  'release_date': '1995-10-02',
  'total_tracks': 40,
  'url': 'https://open.spotify.com/album/1VW1MFNstaJuygaoTPkdCk',
  'artist_name': 'Oasis'},
 {'album_id': '2UG6T6f0Qc9SaBCIcaviLM',
  'name': 'Teenage Dream',
  'release_date': '2010-01-01',
  'total_tracks': 12,
  'url': 'https://open.spotify.com/album/2UG6T6f0Qc9SaBCIcaviLM',
  'artist_name': 'Katy Perry'},
 {'album_id': '18qJgKH8dyYe2RRp6TbnNY',
  'name': 'you seem pretty sad for a girl so in love',
  'release_date': '2026-06-11',
  'total_tracks': 13,
  'url': 'https://open.spotify.com/album/18qJgKH8dyYe2RRp6TbnNY',
  'artist_name': 'Olivia Rodrigo'},
 {'album_id': '7mvXPtV4jvA1hp5Wx2FAJA',
  'name': 'I Barely Know Her',
  'release_date': '2025-08-22',
  'total_tracks': 10,
  'url': 'https://open.spotify.com/album/7mvXPtV4jvA1hp5Wx2FAJA',
  'artist_name': 'sombr'},
 {'album_id': '3WZZF72ihlKPZBS4zSsNHl',
  'name': 'you seem pretty sad for a girl so in love',
  'release_date': '2026-06-12',
  'total_tracks': 13,
  'url': 'https://open.spotify.com/album/3WZZF72ihlKPZBS4zSsNHl',
  'artist_name': 'Olivia Rodrigo'},
 {'album_id': '4UMjBXcRqIgMZ1XumU2x5T',
  'name': 'Dizzy up the Girl',
  'release_date': '1998',
  'total_tracks': 13,
  'url': 'https://open.spotify.com/album/4UMjBXcRqIgMZ1XumU2x5T',
  'artist_name': 'The Goo Goo Dolls'},
 {'album_id': '6nrtxtgaD9zSYBl9APvOCH',
  'name': 'Dandelion',
  'release_date': '2026-04-10',
  'total_tracks': 18,
  'url': 'https://open.spotify.com/album/6nrtxtgaD9zSYBl9APvOCH',
  'artist_name': 'Ella Langley'},
 {'album_id': '18qJgKH8dyYe2RRp6TbnNY',
  'name': 'you seem pretty sad for a girl so in love',
  'release_date': '2026-06-11',
  'total_tracks': 13,
  'url': 'https://open.spotify.com/album/18qJgKH8dyYe2RRp6TbnNY',
  'artist_name': 'Olivia Rodrigo'},
 {'album_id': '4JDXBZdRPId4devseaAOKH',
  'name': 'DECIDE',
  'release_date': '2022-09-16',
  'total_tracks': 13,
  'url': 'https://open.spotify.com/album/4JDXBZdRPId4devseaAOKH',
  'artist_name': 'Djo'},
 {'album_id': '2ANVost0y2y52ema1E9xAZ',
  'name': 'Thriller',
  'release_date': '1982-11-30',
  'total_tracks': 9,
  'url': 'https://open.spotify.com/album/2ANVost0y2y52ema1E9xAZ',
  'artist_name': 'Michael Jackson'},
 {'album_id': '2MHUaRi9OCyTN02SoyRRBJ',
  'name': 'MAYHEM',
  'release_date': '2025-03-07',
  'total_tracks': 14,
  'url': 'https://open.spotify.com/album/2MHUaRi9OCyTN02SoyRRBJ',
  'artist_name': 'Lady Gaga'},
 {'album_id': '0l8zYqoUeBYg47Gmevq9HZ',
  'name': 'The Art of Loving',
  'release_date': '2025-09-26',
  'total_tracks': 12,
  'url': 'https://open.spotify.com/album/0l8zYqoUeBYg47Gmevq9HZ',
  'artist_name': 'Olivia Dean'},
 {'album_id': '1ne2D0NxoGyZd31gAM4HNd',
  'name': 'Illuminate',
  'release_date': '2017-04-20',
  'total_tracks': 13,
  'url': 'https://open.spotify.com/album/1ne2D0NxoGyZd31gAM4HNd',
  'artist_name': 'Shawn Mendes'},
 {'album_id': '1uE3dRPe3SrGdNhd1nWlSa',
  'name': "Bird's Eye",
  'release_date': '2024-08-09',
  'total_tracks': 11,
  'url': 'https://open.spotify.com/album/1uE3dRPe3SrGdNhd1nWlSa',
  'artist_name': 'Ravyn Lenae'},
 {'album_id': '4a6NzYL1YHRUgx9e3YZI6I',
  'name': 'The Life of a Showgirl',
  'release_date': '2025-10-03',
  'total_tracks': 12,
  'url': 'https://open.spotify.com/album/4a6NzYL1YHRUgx9e3YZI6I',
  'artist_name': 'Taylor Swift'},
 {'album_id': '5K79FLRUCSysQnVESLcTdb',
  'name': 'DeBÍ TiRAR MáS FOToS',
  'release_date': '2025-01-05',
  'total_tracks': 17,
  'url': 'https://open.spotify.com/album/5K79FLRUCSysQnVESLcTdb',
  'artist_name': 'Bad Bunny'},
 {'album_id': '4xkM0BwLM9H2IUcbYzpcBI',
  'name': 'I Love You.',
  'release_date': '2013-04-22',
  'total_tracks': 11,
  'url': 'https://open.spotify.com/album/4xkM0BwLM9H2IUcbYzpcBI',
  'artist_name': 'The Neighbourhood'},
 {'album_id': '1eCGY9WJpYgtaFh1Lk2KNo',
  'name': "You'll Be Alright, Kid (Chapter 1)",
  'release_date': '2024-09-26',
  'total_tracks': 11,
  'url': 'https://open.spotify.com/album/1eCGY9WJpYgtaFh1Lk2KNo',
  'artist_name': 'Alex Warren'},
 {'album_id': '5ZX3Zdp20YCGI4ruAfZlMj',
  'name': 'Jamaican (Bam Bam)',
  'release_date': '2025-11-07',
  'total_tracks': 1,
  'url': 'https://open.spotify.com/album/5ZX3Zdp20YCGI4ruAfZlMj',
  'artist_name': 'HUGEL, SOLTO (FR)'},
 {'album_id': '5W9OT0a5iZlBr83a9WMKFY',
  'name': 'Synchronicity (Remastered 2003)',
  'release_date': '1983-06-17',
  'total_tracks': 11,
  'url': 'https://open.spotify.com/album/5W9OT0a5iZlBr83a9WMKFY',
  'artist_name': 'The Police'},
 {'album_id': '4piJq7R3gjUOxnYs6lDCTg',
  'name': 'Hot Fuss',
  'release_date': '2004',
  'total_tracks': 12,
  'url': 'https://open.spotify.com/album/4piJq7R3gjUOxnYs6lDCTg',
  'artist_name': 'The Killers'},
 {'album_id': '25hlG9lEbc2ARvZXY4ZDhv',
  'name': 'Sesi Potret',
  'release_date': '2026-01-29',
  'total_tracks': 1,
  'url': 'https://open.spotify.com/album/25hlG9lEbc2ARvZXY4ZDhv',
  'artist_name': 'eńau, Ari Lesmana'},
 {'album_id': '7vI4iTxDmgEN63liQHPEX1',
  'name': 'The Romantic',
  'release_date': '2026-02-27',
  'total_tracks': 9,
  'url': 'https://open.spotify.com/album/7vI4iTxDmgEN63liQHPEX1',
  'artist_name': 'Bruno Mars'},
 {'album_id': '7aJuG4TFXa2hmE4z1yxc3n',
  'name': 'HIT ME HARD AND SOFT',
  'release_date': '2024-05-17',
  'total_tracks': 10,
  'url': 'https://open.spotify.com/album/7aJuG4TFXa2hmE4z1yxc3n',
  'artist_name': 'Billie Eilish'},
 {'album_id': '6f6tko6NWoH00cyFOl4VYQ',
  'name': 'The Divine Feminine',
  'release_date': '2016-09-16',
  'total_tracks': 10,
  'url': 'https://open.spotify.com/album/6f6tko6NWoH00cyFOl4VYQ',
  'artist_name': 'Mac Miller'},
 {'album_id': '1FZKIm3JVDCxTchXDo5jOV',
  'name': 'Harry Styles',
  'release_date': '2017-05-12',
  'total_tracks': 10,
  'url': 'https://open.spotify.com/album/1FZKIm3JVDCxTchXDo5jOV',
  'artist_name': 'Harry Styles'},
 {'album_id': '58vZavXqh1P5uoTXteudWl',
  'name': 'At The Beach, In Every Life',
  'release_date': '2025-04-25',
  'total_tracks': 12,
  'url': 'https://open.spotify.com/album/58vZavXqh1P5uoTXteudWl',
  'artist_name': 'Gigi Perez'},
 {'album_id': '58ufpQsJ1DS5kq4hhzQDiI',
  'name': 'Unorthodox Jukebox',
  'release_date': '2012-12-07',
  'total_tracks': 10,
  'url': 'https://open.spotify.com/album/58ufpQsJ1DS5kq4hhzQDiI',
  'artist_name': 'Bruno Mars'},
 {'album_id': '1lKquzZlhL5AWMHTeGej4M',
  'name': 'CUARTO AZUL',
  'release_date': '2025-05-29',
  'total_tracks': 19,
  'url': 'https://open.spotify.com/album/1lKquzZlhL5AWMHTeGej4M',
  'artist_name': 'Aitana'},
 {'album_id': '24f1GFXCkViGoRpmGqlSSl',
  'name': 'The Boy Who Played the Harp',
  'release_date': '2025-10-23',
  'total_tracks': 10,
  'url': 'https://open.spotify.com/album/24f1GFXCkViGoRpmGqlSSl',
  'artist_name': 'Dave'},
 {'album_id': '6KFq3hJB6JnNvDbEHRvPoK',
  'name': 'Dracula (Remix)',
  'release_date': '2026-02-06',
  'total_tracks': 2,
  'url': 'https://open.spotify.com/album/6KFq3hJB6JnNvDbEHRvPoK',
  'artist_name': 'Tame Impala, JENNIE'},
 {'album_id': '0OAv7DCME2AV4q1KPO95HY',
  'name': 'ICEMAN',
  'release_date': '2026-05-15',
  'total_tracks': 18,
  'url': 'https://open.spotify.com/album/0OAv7DCME2AV4q1KPO95HY',
  'artist_name': 'Drake'},
 {'album_id': '0l8zYqoUeBYg47Gmevq9HZ',
  'name': 'The Art of Loving',
  'release_date': '2025-09-26',
  'total_tracks': 12,
  'url': 'https://open.spotify.com/album/0l8zYqoUeBYg47Gmevq9HZ',
  'artist_name': 'Olivia Dean'},
 {'album_id': '5YLRVHDVRw3QqWbeTGpC5B',
  'name': 'So Good',
  'release_date': '2017-03-17',
  'total_tracks': 15,
  'url': 'https://open.spotify.com/album/5YLRVHDVRw3QqWbeTGpC5B',
  'artist_name': 'Zara Larsson'},
 {'album_id': '3gBVdu4a1MMJVMy6vwPEb8',
  'name': 'Pablo Honey',
  'release_date': '1993-02-22',
  'total_tracks': 12,
  'url': 'https://open.spotify.com/album/3gBVdu4a1MMJVMy6vwPEb8',
  'artist_name': 'Radiohead'},
 {'album_id': '5K79FLRUCSysQnVESLcTdb',
  'name': 'DeBÍ TiRAR MáS FOToS',
  'release_date': '2025-01-05',
  'total_tracks': 17,
  'url': 'https://open.spotify.com/album/5K79FLRUCSysQnVESLcTdb',
  'artist_name': 'Bad Bunny'},
 {'album_id': '5K79FLRUCSysQnVESLcTdb',
  'name': 'DeBÍ TiRAR MáS FOToS',
  'release_date': '2025-01-05',
  'total_tracks': 17,
  'url': 'https://open.spotify.com/album/5K79FLRUCSysQnVESLcTdb',
  'artist_name': 'Bad Bunny'},
 {'album_id': '2cHhcN6iNLNXc7FByWBGi5',
  'name': 'Oral Fixation, Vol. 2 (Expanded Edition)',
  'release_date': '2005-11-28',
  'total_tracks': 16,
  'url': 'https://open.spotify.com/album/2cHhcN6iNLNXc7FByWBGi5',
  'artist_name': 'Shakira'},
 {'album_id': '2biVG6BYnVVSwLYd1OjbPT',
  'name': 'Dream Your Life Away (Deluxe Edition)',
  'release_date': '2014-08-05',
  'total_tracks': 20,
  'url': 'https://open.spotify.com/album/2biVG6BYnVVSwLYd1OjbPT',
  'artist_name': 'Vance Joy'},
 {'album_id': '40GMAhriYJRO1rsY4YdrZb',
  'name': 'Views',
  'release_date': '2016-05-06',
  'total_tracks': 20,
  'url': 'https://open.spotify.com/album/40GMAhriYJRO1rsY4YdrZb',
  'artist_name': 'Drake'},
 {'album_id': '3sysiYphqNRQw7VKLCg1yE',
  'name': 'Love?',
  'release_date': '2011-04-29',
  'total_tracks': 17,
  'url': 'https://open.spotify.com/album/3sysiYphqNRQw7VKLCg1yE',
  'artist_name': 'Jennifer Lopez'}]

In [12]:
data['items'][0]['item']['album']['artists'][0]

{'external_urls': {'spotify': 'https://open.spotify.com/artist/0EmeFodog0BfCgMzAIvKQp'},
 'href': 'https://api.spotify.com/v1/artists/0EmeFodog0BfCgMzAIvKQp',
 'id': '0EmeFodog0BfCgMzAIvKQp',
 'name': 'Shakira',
 'type': 'artist',
 'uri': 'spotify:artist:0EmeFodog0BfCgMzAIvKQp'}

In [13]:
artist_list = []
for row in data['items']:
    artists = row['item']['artists']

    for artist in artists:
        artist_id = artist['id']
        artist_name = artist['name']
        artist_url = artist['href']

        artist_element = {
            'artist_id': artist_id,
            'artist_name': artist_name,
            'external_url': artist_url
        }

        artist_list.append(artist_element)

artist_list

[{'artist_id': '0EmeFodog0BfCgMzAIvKQp',
  'artist_name': 'Shakira',
  'external_url': 'https://api.spotify.com/v1/artists/0EmeFodog0BfCgMzAIvKQp'},
 {'artist_id': '3wcj11K77LjEY1PkEazffa',
  'artist_name': 'Burna Boy',
  'external_url': 'https://api.spotify.com/v1/artists/3wcj11K77LjEY1PkEazffa'},
 {'artist_id': '1uNFoZAHBGtllmzznpCI3s',
  'artist_name': 'Justin Bieber',
  'external_url': 'https://api.spotify.com/v1/artists/1uNFoZAHBGtllmzznpCI3s'},
 {'artist_id': '0hCNtLu0JehylgoiP8L4Gh',
  'artist_name': 'Nicki Minaj',
  'external_url': 'https://api.spotify.com/v1/artists/0hCNtLu0JehylgoiP8L4Gh'},
 {'artist_id': '66CXWjxzNUsdJxJ2JdwvnR',
  'artist_name': 'Ariana Grande',
  'external_url': 'https://api.spotify.com/v1/artists/66CXWjxzNUsdJxJ2JdwvnR'},
 {'artist_id': '3Nrfpe0tUJi4K4DXYWgMUX',
  'artist_name': 'BTS',
  'external_url': 'https://api.spotify.com/v1/artists/3Nrfpe0tUJi4K4DXYWgMUX'},
 {'artist_id': '7eKkW1zo5uzW8kUntiiBvz',
  'artist_name': 'Malcolm Todd',
  'external_url': 'https://api.spotify.com/v1/artists/7eKkW1zo5uzW8kUntiiBvz'},
 {'artist_id': '3fMbdgg4jU18AjLCKBhRSm',
  'artist_name': 'Michael Jackson',
  'external_url': 'https://api.spotify.com/v1/artists/3fMbdgg4jU18AjLCKBhRSm'},
 {'artist_id': '3c0gDdb9lhnHGFtP4prQpn',
  'artist_name': 'KATSEYE',
  'external_url': 'https://api.spotify.com/v1/artists/3c0gDdb9lhnHGFtP4prQpn'},
 {'artist_id': '6USv9qhCn6zfxlBQIYJ9qs',
  'artist_name': 'Dominic Fike',
  'external_url': 'https://api.spotify.com/v1/artists/6USv9qhCn6zfxlBQIYJ9qs'},
 {'artist_id': '5mHUmlJWkcoOk1NbjfrXWz',
  'artist_name': 'Temper City',
  'external_url': 'https://api.spotify.com/v1/artists/5mHUmlJWkcoOk1NbjfrXWz'},
 {'artist_id': '2DaxqgrOhkeH0fpeiQq2f4',
  'artist_name': 'Oasis',
  'external_url': 'https://api.spotify.com/v1/artists/2DaxqgrOhkeH0fpeiQq2f4'},
 {'artist_id': '6jJ0s89eD6GaHleKKya26X',
  'artist_name': 'Katy Perry',
  'external_url': 'https://api.spotify.com/v1/artists/6jJ0s89eD6GaHleKKya26X'},
 {'artist_id': '1McMsnEElThX1knmY4oliG',
  'artist_name': 'Olivia Rodrigo',
  'external_url': 'https://api.spotify.com/v1/artists/1McMsnEElThX1knmY4oliG'},
 {'artist_id': '4G9NDjRyZFDlJKMRL8hx3S',
  'artist_name': 'sombr',
  'external_url': 'https://api.spotify.com/v1/artists/4G9NDjRyZFDlJKMRL8hx3S'},
 {'artist_id': '1McMsnEElThX1knmY4oliG',
  'artist_name': 'Olivia Rodrigo',
  'external_url': 'https://api.spotify.com/v1/artists/1McMsnEElThX1knmY4oliG'},
 {'artist_id': '2sil8z5kiy4r76CRTXxBCA',
  'artist_name': 'The Goo Goo Dolls',
  'external_url': 'https://api.spotify.com/v1/artists/2sil8z5kiy4r76CRTXxBCA'},
 {'artist_id': '6BRxQ8cD3eqnrVj6WKDok8',
  'artist_name': 'Ella Langley',
  'external_url': 'https://api.spotify.com/v1/artists/6BRxQ8cD3eqnrVj6WKDok8'},
 {'artist_id': '1McMsnEElThX1knmY4oliG',
  'artist_name': 'Olivia Rodrigo',
  'external_url': 'https://api.spotify.com/v1/artists/1McMsnEElThX1knmY4oliG'},
 {'artist_id': '5p9HO3XC5P3BLxJs5Mtrhm',
  'artist_name': 'Djo',
  'external_url': 'https://api.spotify.com/v1/artists/5p9HO3XC5P3BLxJs5Mtrhm'},
 {'artist_id': '3fMbdgg4jU18AjLCKBhRSm',
  'artist_name': 'Michael Jackson',
  'external_url': 'https://api.spotify.com/v1/artists/3fMbdgg4jU18AjLCKBhRSm'},
 {'artist_id': '1HY2Jd0NmPuamShAr6KMms',
  'artist_name': 'Lady Gaga',
  'external_url': 'https://api.spotify.com/v1/artists/1HY2Jd0NmPuamShAr6KMms'},
 {'artist_id': '0du5cEVh5yTK9QJze8zA0C',
  'artist_name': 'Bruno Mars',
  'external_url': 'https://api.spotify.com/v1/artists/0du5cEVh5yTK9QJze8zA0C'},
 {'artist_id': '00x1fYSGhdqScXBRpSj3DW',
  'artist_name': 'Olivia Dean',
  'external_url': 'https://api.spotify.com/v1/artists/00x1fYSGhdqScXBRpSj3DW'},
 {'artist_id': '7n2wHs1TKAczGzO7Dd2rGr',
  'artist_name': 'Shawn Mendes',
  'external_url': 'https://api.spotify.com/v1/artists/7n2wHs1TKAczGzO7Dd2rGr'},
 {'artist_id': '5RTLRtXjbXI2lSXc6jxlAz',
  'artist_name': 'Ravyn Lenae',
  'external_url': 'https://api.spotify.com/v1/artists/5RTLRtXjbXI2lSXc6jxlAz'},
 {'artist_id': '06HL4z0CvFAxyc27GXpf02',
  'artist_name': 'Taylor Swift',
  'external_url': 'https://api.spotify.com/v1/artists/06HL4z0CvFAxyc27GXpf02'},
 {'artist_id': '4q3ewBCX7sLwd24euuV69X',
  'artist_name': 'Bad Bunny',
  'external_url': 'https://api.spotify.com/v1/artists/4q3ewBCX7sLwd24euuV69X'},
 {'artist_id': '77SW9BnxLY8rJ0RciFqkHh',
  'artist_name': 'The Neighbourhood',
  'external_url': 'https://api.spotify.com/v1/artists/77SW9BnxLY8rJ0RciFqkHh'},
 {'artist_id': '0fTSzq9jAh4c36UVb4V7CB',
  'artist_name': 'Alex Warren',
  'external_url': 'https://api.spotify.com/v1/artists/0fTSzq9jAh4c36UVb4V7CB'},
 {'artist_id': '5PlfkPxwCpRRWQJBxCa0By',
  'artist_name': 'HUGEL',
  'external_url': 'https://api.spotify.com/v1/artists/5PlfkPxwCpRRWQJBxCa0By'},
 {'artist_id': '0F3tUZeb9dLNEpxCpzEBQt',
  'artist_name': 'SOLTO (FR)',
  'external_url': 'https://api.spotify.com/v1/artists/0F3tUZeb9dLNEpxCpzEBQt'},
 {'artist_id': '5NGO30tJxFlKixkPSgXcFE',
  'artist_name': 'The Police',
  'external_url': 'https://api.spotify.com/v1/artists/5NGO30tJxFlKixkPSgXcFE'},
 {'artist_id': '0C0XlULifJtAgn6ZNCW2eu',
  'artist_name': 'The Killers',
  'external_url': 'https://api.spotify.com/v1/artists/0C0XlULifJtAgn6ZNCW2eu'},
 {'artist_id': '0agUNq8PH1QSgm88EuhM1u',
  'artist_name': 'eńau',
  'external_url': 'https://api.spotify.com/v1/artists/0agUNq8PH1QSgm88EuhM1u'},
 {'artist_id': '3MMDw11m6HJrXlGOE3honc',
  'artist_name': 'Ari Lesmana',
  'external_url': 'https://api.spotify.com/v1/artists/3MMDw11m6HJrXlGOE3honc'},
 {'artist_id': '0du5cEVh5yTK9QJze8zA0C',
  'artist_name': 'Bruno Mars',
  'external_url': 'https://api.spotify.com/v1/artists/0du5cEVh5yTK9QJze8zA0C'},
 {'artist_id': '6qqNVTkY8uBg9cP3Jd7DAH',
  'artist_name': 'Billie Eilish',
  'external_url': 'https://api.spotify.com/v1/artists/6qqNVTkY8uBg9cP3Jd7DAH'},
 {'artist_id': '4LLpKhyESsyAXpc4laK94U',
  'artist_name': 'Mac Miller',
  'external_url': 'https://api.spotify.com/v1/artists/4LLpKhyESsyAXpc4laK94U'},
 {'artist_id': '7c0XG5cIJTrrAgEC3ULPiq',
  'artist_name': 'Ty Dolla $ign',
  'external_url': 'https://api.spotify.com/v1/artists/7c0XG5cIJTrrAgEC3ULPiq'},
 {'artist_id': '6KImCVD70vtIoJWnq6nGn3',
  'artist_name': 'Harry Styles',
  'external_url': 'https://api.spotify.com/v1/artists/6KImCVD70vtIoJWnq6nGn3'},
 {'artist_id': '1iCnM8foFssWlPRLfAbIwo',
  'artist_name': 'Gigi Perez',
  'external_url': 'https://api.spotify.com/v1/artists/1iCnM8foFssWlPRLfAbIwo'},
 {'artist_id': '0du5cEVh5yTK9QJze8zA0C',
  'artist_name': 'Bruno Mars',
  'external_url': 'https://api.spotify.com/v1/artists/0du5cEVh5yTK9QJze8zA0C'},
 {'artist_id': '7eLcDZDYHXZCebtQmVFL25',
  'artist_name': 'Aitana',
  'external_url': 'https://api.spotify.com/v1/artists/7eLcDZDYHXZCebtQmVFL25'},
 {'artist_id': '6Ip8FS7vWT1uKkJSweANQK',
  'artist_name': 'Dave',
  'external_url': 'https://api.spotify.com/v1/artists/6Ip8FS7vWT1uKkJSweANQK'},
 {'artist_id': '687cZJR45JO7jhk1LHIbgq',
  'artist_name': 'Tems',
  'external_url': 'https://api.spotify.com/v1/artists/687cZJR45JO7jhk1LHIbgq'},
 {'artist_id': '5INjqkS1o8h1imAzPqGZBb',
  'artist_name': 'Tame Impala',
  'external_url': 'https://api.spotify.com/v1/artists/5INjqkS1o8h1imAzPqGZBb'},
 {'artist_id': '250b0Wlc5Vk0CoUsaCY84M',
  'artist_name': 'JENNIE',
  'external_url': 'https://api.spotify.com/v1/artists/250b0Wlc5Vk0CoUsaCY84M'},
 {'artist_id': '3TVXtAsR1Inumwj472S9r4',
  'artist_name': 'Drake',
  'external_url': 'https://api.spotify.com/v1/artists/3TVXtAsR1Inumwj472S9r4'},
 {'artist_id': '00x1fYSGhdqScXBRpSj3DW',
  'artist_name': 'Olivia Dean',
  'external_url': 'https://api.spotify.com/v1/artists/00x1fYSGhdqScXBRpSj3DW'},
 {'artist_id': '1Xylc3o4UrD53lo9CvFvVg',
  'artist_name': 'Zara Larsson',
  'external_url': 'https://api.spotify.com/v1/artists/1Xylc3o4UrD53lo9CvFvVg'},
 {'artist_id': '4Z8W4fKeB5YxbusRsdQVPb',
  'artist_name': 'Radiohead',
  'external_url': 'https://api.spotify.com/v1/artists/4Z8W4fKeB5YxbusRsdQVPb'},
 {'artist_id': '4q3ewBCX7sLwd24euuV69X',
  'artist_name': 'Bad Bunny',
  'external_url': 'https://api.spotify.com/v1/artists/4q3ewBCX7sLwd24euuV69X'},
 {'artist_id': '4q3ewBCX7sLwd24euuV69X',
  'artist_name': 'Bad Bunny',
  'external_url': 'https://api.spotify.com/v1/artists/4q3ewBCX7sLwd24euuV69X'},
 {'artist_id': '0EmeFodog0BfCgMzAIvKQp',
  'artist_name': 'Shakira',
  'external_url': 'https://api.spotify.com/v1/artists/0EmeFodog0BfCgMzAIvKQp'},
 {'artist_id': '7aBzpmFXB4WWpPl2F7RjBe',
  'artist_name': 'Wyclef Jean',
  'external_url': 'https://api.spotify.com/v1/artists/7aBzpmFXB4WWpPl2F7RjBe'},
 {'artist_id': '10exVja0key0uqUkk6LJRT',
  'artist_name': 'Vance Joy',
  'external_url': 'https://api.spotify.com/v1/artists/10exVja0key0uqUkk6LJRT'},
 {'artist_id': '3TVXtAsR1Inumwj472S9r4',
  'artist_name': 'Drake',
  'external_url': 'https://api.spotify.com/v1/artists/3TVXtAsR1Inumwj472S9r4'},
 {'artist_id': '3tVQdUvClmAT7URs9V3rsp',
  'artist_name': 'Wizkid',
  'external_url': 'https://api.spotify.com/v1/artists/3tVQdUvClmAT7URs9V3rsp'},
 {'artist_id': '6TK7fjRPdy2GW2pJzNF23L',
  'artist_name': 'Kyla',
  'external_url': 'https://api.spotify.com/v1/artists/6TK7fjRPdy2GW2pJzNF23L'},
 {'artist_id': '2DlGxzQSjYe5N6G9nkYghR',
  'artist_name': 'Jennifer Lopez',
  'external_url': 'https://api.spotify.com/v1/artists/2DlGxzQSjYe5N6G9nkYghR'},
 {'artist_id': '0TnOYISbd1XYRBk9myaseg',
  'artist_name': 'Pitbull',
  'external_url': 'https://api.spotify.com/v1/artists/0TnOYISbd1XYRBk9myaseg'}]

In [14]:
import random
song_list = []

for row in data['items']:
    song = row['item']

    song_id = song['id']
    song_name = song['name']
    song_duration = song['duration_ms']
    song_url = song['external_urls']['spotify']
    song_added = row['added_at']
    album_id = song['album']['id']
    artist_id = ", ".join(
        artist['id'] for artist in song['artists']
    )

    song_element = {
        'song_id': song_id,
        'song_name': song_name,
        'duration_ms': song_duration,
        'url': song_url,
        'song_added': song_added,
        'album_id': album_id,
        'artist_id': artist_id,
        'song_popularity': random.randint(75, 95)
    }

    song_list.append(song_element)

song_list

[{'song_id': '0kosUz0jePvjiz4ctmR6wL',
  'song_name': 'Dai Dai',
  'duration_ms': 223448,
  'url': 'https://open.spotify.com/track/0kosUz0jePvjiz4ctmR6wL',
  'song_added': '2026-07-31T12:48:02Z',
  'album_id': '2eeufspLkAubwTJfOGSrI8',
  'artist_id': '0EmeFodog0BfCgMzAIvKQp, 3wcj11K77LjEY1PkEazffa',
  'song_popularity': 81},
 {'song_id': '6QFCMUUq1T2Vf5sFUXcuQ7',
  'song_name': 'Beauty And A Beat',
  'duration_ms': 227986,
  'url': 'https://open.spotify.com/track/6QFCMUUq1T2Vf5sFUXcuQ7',
  'song_added': '2026-07-31T12:48:02Z',
  'album_id': '5cxMa6oLINJzmZ8lF7wWQN',
  'artist_id': '1uNFoZAHBGtllmzznpCI3s, 0hCNtLu0JehylgoiP8L4Gh',
  'song_popularity': 91},
 {'song_id': '20jbSiX29FDX4oQxBXyUEi',
  'song_name': 'hate that i made you love me',
  'duration_ms': 197949,
  'url': 'https://open.spotify.com/track/20jbSiX29FDX4oQxBXyUEi',
  'song_added': '2026-07-31T12:48:02Z',
  'album_id': '1x159B5VzbDWAGBik5cr1z',
  'artist_id': '66CXWjxzNUsdJxJ2JdwvnR',
  'song_popularity': 91},
 {'song_id': '68lbSrXDORS51pmyjZv712',
  'song_name': 'SWIM',
  'duration_ms': 159007,
  'url': 'https://open.spotify.com/track/68lbSrXDORS51pmyjZv712',
  'song_added': '2026-07-31T12:48:02Z',
  'album_id': '3ukkRHDHbN8tNRPKsGZR1h',
  'artist_id': '3Nrfpe0tUJi4K4DXYWgMUX',
  'song_popularity': 87},
 {'song_id': '0eAuGrXyGFYwur9ARUe7LJ',
  'song_name': 'Earrings',
  'duration_ms': 151500,
  'url': 'https://open.spotify.com/track/0eAuGrXyGFYwur9ARUe7LJ',
  'song_added': '2026-07-31T12:48:02Z',
  'album_id': '2jX6yKrWw9bY7JAYHhhtqZ',
  'artist_id': '7eKkW1zo5uzW8kUntiiBvz',
  'song_popularity': 90},
 {'song_id': '7J1uxwnxfQLu4APicE5Rnj',
  'song_name': 'Billie Jean',
  'duration_ms': 293802,
  'url': 'https://open.spotify.com/track/7J1uxwnxfQLu4APicE5Rnj',
  'song_added': '2026-07-31T12:48:02Z',
  'album_id': '2ANVost0y2y52ema1E9xAZ',
  'artist_id': '3fMbdgg4jU18AjLCKBhRSm',
  'song_popularity': 93},
 {'song_id': '3ouNEk0tv5TTi8VWMe1xbX',
  'song_name': 'Animal',
  'duration_ms': 158494,
  'url': 'https://open.spotify.com/track/3ouNEk0tv5TTi8VWMe1xbX',
  'song_added': '2026-07-31T12:48:02Z',
  'album_id': '3ybCwWDhYDt2GYSCYFiF83',
  'artist_id': '3c0gDdb9lhnHGFtP4prQpn',
  'song_popularity': 88},
 {'song_id': '7yNf9YjeO5JXUE3JEBgnYc',
  'song_name': 'Babydoll',
  'duration_ms': 97960,
  'url': 'https://open.spotify.com/track/7yNf9YjeO5JXUE3JEBgnYc',
  'song_added': '2026-07-31T12:48:02Z',
  'album_id': '05jbNkYoEQdjVDHEHtg1gY',
  'artist_id': '6USv9qhCn6zfxlBQIYJ9qs',
  'song_popularity': 95},
 {'song_id': '4qW3BbQAwZsrnu8a3ZRdyT',
  'song_name': 'Self Aware',
  'duration_ms': 180740,
  'url': 'https://open.spotify.com/track/4qW3BbQAwZsrnu8a3ZRdyT',
  'song_added': '2026-07-31T12:48:02Z',
  'album_id': '7Cdqksm4yTfiq0EfKPa86M',
  'artist_id': '5mHUmlJWkcoOk1NbjfrXWz',
  'song_popularity': 79},
 {'song_id': '5qqabIl2vWzo9ApSC317sa',
  'song_name': 'Wonderwall - Remastered',
  'duration_ms': 258773,
  'url': 'https://open.spotify.com/track/5qqabIl2vWzo9ApSC317sa',
  'song_added': '2026-07-31T12:48:02Z',
  'album_id': '1VW1MFNstaJuygaoTPkdCk',
  'artist_id': '2DaxqgrOhkeH0fpeiQq2f4',
  'song_popularity': 93},
 {'song_id': '2009X8GyWTqyxIdzAEYW6N',
  'song_name': 'The One That Got Away',
  'duration_ms': 227333,
  'url': 'https://open.spotify.com/track/2009X8GyWTqyxIdzAEYW6N',
  'song_added': '2026-07-31T12:48:02Z',
  'album_id': '2UG6T6f0Qc9SaBCIcaviLM',
  'artist_id': '6jJ0s89eD6GaHleKKya26X',
  'song_popularity': 75},
 {'song_id': '49j6SvuvWfbEKZKzsHCdLJ',
  'song_name': 'stupid song',
  'duration_ms': 209680,
  'url': 'https://open.spotify.com/track/49j6SvuvWfbEKZKzsHCdLJ',
  'song_added': '2026-07-31T12:48:02Z',
  'album_id': '18qJgKH8dyYe2RRp6TbnNY',
  'artist_id': '1McMsnEElThX1knmY4oliG',
  'song_popularity': 93},
 {'song_id': '7qjZnBKE73H4Oxkopwulqe',
  'song_name': 'back to friends',
  'duration_ms': 199032,
  'url': 'https://open.spotify.com/track/7qjZnBKE73H4Oxkopwulqe',
  'song_added': '2026-07-31T12:48:02Z',
  'album_id': '7mvXPtV4jvA1hp5Wx2FAJA',
  'artist_id': '4G9NDjRyZFDlJKMRL8hx3S',
  'song_popularity': 93},
 {'song_id': '55pBIZO1cqoldeqpp5WR7H',
  'song_name': 'the cure',
  'duration_ms': 297090,
  'url': 'https://open.spotify.com/track/55pBIZO1cqoldeqpp5WR7H',
  'song_added': '2026-07-31T12:48:02Z',
  'album_id': '3WZZF72ihlKPZBS4zSsNHl',
  'artist_id': '1McMsnEElThX1knmY4oliG',
  'song_popularity': 89},
 {'song_id': '6Qyc6fS4DsZjB2mRW9DsQs',
  'song_name': 'Iris',
  'duration_ms': 289533,
  'url': 'https://open.spotify.com/track/6Qyc6fS4DsZjB2mRW9DsQs',
  'song_added': '2026-07-31T12:48:02Z',
  'album_id': '4UMjBXcRqIgMZ1XumU2x5T',
  'artist_id': '2sil8z5kiy4r76CRTXxBCA',
  'song_popularity': 85},
 {'song_id': '7scFxt9VhL4FJwuPSfRlfN',
  'song_name': "Choosin' Texas",
  'duration_ms': 231746,
  'url': 'https://open.spotify.com/track/7scFxt9VhL4FJwuPSfRlfN',
  'song_added': '2026-07-31T12:48:02Z',
  'album_id': '6nrtxtgaD9zSYBl9APvOCH',
  'artist_id': '6BRxQ8cD3eqnrVj6WKDok8',
  'song_popularity': 87},
 {'song_id': '3fRCAPMMZ8l8P9YKI6OCzD',
  'song_name': 'drop dead',
  'duration_ms': 224998,
  'url': 'https://open.spotify.com/track/3fRCAPMMZ8l8P9YKI6OCzD',
  'song_added': '2026-07-31T12:48:02Z',
  'album_id': '18qJgKH8dyYe2RRp6TbnNY',
  'artist_id': '1McMsnEElThX1knmY4oliG',
  'song_popularity': 90},
 {'song_id': '3qhlB30KknSejmIvZZLjOD',
  'song_name': 'End of Beginning',
  'duration_ms': 159245,
  'url': 'https://open.spotify.com/track/3qhlB30KknSejmIvZZLjOD',
  'song_added': '2026-07-31T12:48:02Z',
  'album_id': '4JDXBZdRPId4devseaAOKH',
  'artist_id': '5p9HO3XC5P3BLxJs5Mtrhm',
  'song_popularity': 93},
 {'song_id': '3BovdzfaX4jb5KFQwoPfAw',
  'song_name': 'Beat It',
  'duration_ms': 258296,
  'url': 'https://open.spotify.com/track/3BovdzfaX4jb5KFQwoPfAw',
  'song_added': '2026-07-31T12:48:02Z',
  'album_id': '2ANVost0y2y52ema1E9xAZ',
  'artist_id': '3fMbdgg4jU18AjLCKBhRSm',
  'song_popularity': 80},
 {'song_id': '7so0lgd0zP2Sbgs2d7a1SZ',
  'song_name': 'Die With A Smile',
  'duration_ms': 251667,
  'url': 'https://open.spotify.com/track/7so0lgd0zP2Sbgs2d7a1SZ',
  'song_added': '2026-07-31T12:48:02Z',
  'album_id': '2MHUaRi9OCyTN02SoyRRBJ',
  'artist_id': '1HY2Jd0NmPuamShAr6KMms, 0du5cEVh5yTK9QJze8zA0C',
  'song_popularity': 78},
 {'song_id': '0mYXRQpTGjaLJt1l9MY4ps',
  'song_name': 'Man I Need',
  'duration_ms': 184000,
  'url': 'https://open.spotify.com/track/0mYXRQpTGjaLJt1l9MY4ps',
  'song_added': '2026-07-31T12:48:02Z',
  'album_id': '0l8zYqoUeBYg47Gmevq9HZ',
  'artist_id': '00x1fYSGhdqScXBRpSj3DW',
  'song_popularity': 91},
 {'song_id': '3QGsuHI8jO1Rx4JWLUh9jd',
  'song_name': 'Treat You Better',
  'duration_ms': 187973,
  'url': 'https://open.spotify.com/track/3QGsuHI8jO1Rx4JWLUh9jd',
  'song_added': '2026-07-31T12:48:02Z',
  'album_id': '1ne2D0NxoGyZd31gAM4HNd',
  'artist_id': '7n2wHs1TKAczGzO7Dd2rGr',
  'song_popularity': 77},
 {'song_id': '4WFgvKVfEhb3IUAFGrutTR',
  'song_name': 'Love Me Not',
  'duration_ms': 213466,
  'url': 'https://open.spotify.com/track/4WFgvKVfEhb3IUAFGrutTR',
  'song_added': '2026-07-31T12:48:02Z',
  'album_id': '1uE3dRPe3SrGdNhd1nWlSa',
  'artist_id': '5RTLRtXjbXI2lSXc6jxlAz',
  'song_popularity': 94},
 {'song_id': '53iuhJlwXhSER5J2IYYv1W',
  'song_name': 'The Fate of Ophelia',
  'duration_ms': 226073,
  'url': 'https://open.spotify.com/track/53iuhJlwXhSER5J2IYYv1W',
  'song_added': '2026-07-31T12:48:02Z',
  'album_id': '4a6NzYL1YHRUgx9e3YZI6I',
  'artist_id': '06HL4z0CvFAxyc27GXpf02',
  'song_popularity': 83},
 {'song_id': '3sK8wGT43QFpWrvNQsrQya',
  'song_name': 'DtMF',
  'duration_ms': 237117,
  'url': 'https://open.spotify.com/track/3sK8wGT43QFpWrvNQsrQya',
  'song_added': '2026-07-31T12:48:02Z',
  'album_id': '5K79FLRUCSysQnVESLcTdb',
  'artist_id': '4q3ewBCX7sLwd24euuV69X',
  'song_popularity': 91},
 {'song_id': '2QjOHCTQ1Jl3zawyYOpxh6',
  'song_name': 'Sweater Weather',
  'duration_ms': 240400,
  'url': 'https://open.spotify.com/track/2QjOHCTQ1Jl3zawyYOpxh6',
  'song_added': '2026-07-31T12:48:02Z',
  'album_id': '4xkM0BwLM9H2IUcbYzpcBI',
  'artist_id': '77SW9BnxLY8rJ0RciFqkHh',
  'song_popularity': 92},
 {'song_id': '2RkZ5LkEzeHGRsmDqKwmaJ',
  'song_name': 'Ordinary',
  'duration_ms': 186964,
  'url': 'https://open.spotify.com/track/2RkZ5LkEzeHGRsmDqKwmaJ',
  'song_added': '2026-07-31T12:48:02Z',
  'album_id': '1eCGY9WJpYgtaFh1Lk2KNo',
  'artist_id': '0fTSzq9jAh4c36UVb4V7CB',
  'song_popularity': 81},
 {'song_id': '7e4zDInS6tA2jwzphvs2Ay',
  'song_name': 'Jamaican (Bam Bam)',
  'duration_ms': 156393,
  'url': 'https://open.spotify.com/track/7e4zDInS6tA2jwzphvs2Ay',
  'song_added': '2026-07-31T12:48:02Z',
  'album_id': '5ZX3Zdp20YCGI4ruAfZlMj',
  'artist_id': '5PlfkPxwCpRRWQJBxCa0By, 0F3tUZeb9dLNEpxCpzEBQt',
  'song_popularity': 79},
 {'song_id': '1JSTJqkT5qHq8MDJnJbRE1',
  'song_name': 'Every Breath You Take',
  'duration_ms': 253920,
  'url': 'https://open.spotify.com/track/1JSTJqkT5qHq8MDJnJbRE1',
  'song_added': '2026-07-31T12:48:02Z',
  'album_id': '5W9OT0a5iZlBr83a9WMKFY',
  'artist_id': '5NGO30tJxFlKixkPSgXcFE',
  'song_popularity': 94},
 {'song_id': '003vvx7Niy0yvhvHt4a68B',
  'song_name': 'Mr. Brightside',
  'duration_ms': 222973,
  'url': 'https://open.spotify.com/track/003vvx7Niy0yvhvHt4a68B',
  'song_added': '2026-07-31T12:48:02Z',
  'album_id': '4piJq7R3gjUOxnYs6lDCTg',
  'artist_id': '0C0XlULifJtAgn6ZNCW2eu',
  'song_popularity': 86},
 {'song_id': '4xoY4lZNoTjEuHsSmhgF1G',
  'song_name': 'Sesi Potret',
  'duration_ms': 243000,
  'url': 'https://open.spotify.com/track/4xoY4lZNoTjEuHsSmhgF1G',
  'song_added': '2026-07-31T12:48:02Z',
  'album_id': '25hlG9lEbc2ARvZXY4ZDhv',
  'artist_id': '0agUNq8PH1QSgm88EuhM1u, 3MMDw11m6HJrXlGOE3honc',
  'song_popularity': 92},
 {'song_id': '5y2ijHECwFYWqcAHKTZgzD',
  'song_name': 'Risk It All',
  'duration_ms': 204068,
  'url': 'https://open.spotify.com/track/5y2ijHECwFYWqcAHKTZgzD',
  'song_added': '2026-07-31T12:48:02Z',
  'album_id': '7vI4iTxDmgEN63liQHPEX1',
  'artist_id': '0du5cEVh5yTK9QJze8zA0C',
  'song_popularity': 89},
 {'song_id': '6dOtVTDdiauQNBQEDOtlAB',
  'song_name': 'BIRDS OF A FEATHER',
  'duration_ms': 210373,
  'url': 'https://open.spotify.com/track/6dOtVTDdiauQNBQEDOtlAB',
  'song_added': '2026-07-31T12:48:02Z',
  'album_id': '7aJuG4TFXa2hmE4z1yxc3n',
  'artist_id': '6qqNVTkY8uBg9cP3Jd7DAH',
  'song_popularity': 76},
 {'song_id': '2lpygKqzPFtItQ4ss3cgfb',
  'song_name': 'Cinderella (feat. Ty Dolla $ign)',
  'duration_ms': 480186,
  'url': 'https://open.spotify.com/track/2lpygKqzPFtItQ4ss3cgfb',
  'song_added': '2026-07-31T12:48:02Z',
  'album_id': '6f6tko6NWoH00cyFOl4VYQ',
  'artist_id': '4LLpKhyESsyAXpc4laK94U, 7c0XG5cIJTrrAgEC3ULPiq',
  'song_popularity': 78},
 {'song_id': '5Ohxk2dO5COHF1krpoPigN',
  'song_name': 'Sign of the Times',
  'duration_ms': 340706,
  'url': 'https://open.spotify.com/track/5Ohxk2dO5COHF1krpoPigN',
  'song_added': '2026-07-31T12:48:02Z',
  'album_id': '1FZKIm3JVDCxTchXDo5jOV',
  'artist_id': '6KImCVD70vtIoJWnq6nGn3',
  'song_popularity': 94},
 {'song_id': '21IYMdzTrzSe191Cy5eMap',
  'song_name': 'Sailor Song',
  'duration_ms': 211978,
  'url': 'https://open.spotify.com/track/21IYMdzTrzSe191Cy5eMap',
  'song_added': '2026-07-31T12:48:02Z',
  'album_id': '58vZavXqh1P5uoTXteudWl',
  'artist_id': '1iCnM8foFssWlPRLfAbIwo',
  'song_popularity': 83},
 {'song_id': '3w3y8KPTfNeOKPiqUTakBh',
  'song_name': 'Locked out of Heaven',
  'duration_ms': 233478,
  'url': 'https://open.spotify.com/track/3w3y8KPTfNeOKPiqUTakBh',
  'song_added': '2026-07-31T12:48:02Z',
  'album_id': '58ufpQsJ1DS5kq4hhzQDiI',
  'artist_id': '0du5cEVh5yTK9QJze8zA0C',
  'song_popularity': 90},
 {'song_id': '6hpuesKPNa3WhV48O7Fa47',
  'song_name': 'SUPERESTRELLA',
  'duration_ms': 183529,
  'url': 'https://open.spotify.com/track/6hpuesKPNa3WhV48O7Fa47',
  'song_added': '2026-07-31T12:48:02Z',
  'album_id': '1lKquzZlhL5AWMHTeGej4M',
  'artist_id': '7eLcDZDYHXZCebtQmVFL25',
  'song_popularity': 95},
 {'song_id': '3oTuTpF1F3A7rEC6RKsMRz',
  'song_name': 'Raindance (feat. Tems)',
  'duration_ms': 219743,
  'url': 'https://open.spotify.com/track/3oTuTpF1F3A7rEC6RKsMRz',
  'song_added': '2026-07-31T12:48:02Z',
  'album_id': '24f1GFXCkViGoRpmGqlSSl',
  'artist_id': '6Ip8FS7vWT1uKkJSweANQK, 687cZJR45JO7jhk1LHIbgq',
  'song_popularity': 77},
 {'song_id': '5yvVYFDUpbnjcnRBgjwTzM',
  'song_name': 'Dracula - JENNIE Remix',
  'duration_ms': 209720,
  'url': 'https://open.spotify.com/track/5yvVYFDUpbnjcnRBgjwTzM',
  'song_added': '2026-07-31T12:48:02Z',
  'album_id': '6KFq3hJB6JnNvDbEHRvPoK',
  'artist_id': '5INjqkS1o8h1imAzPqGZBb, 250b0Wlc5Vk0CoUsaCY84M',
  'song_popularity': 77},
 {'song_id': '514joG57v4yKTsfQmz7stz',
  'song_name': 'Janice STFU',
  'duration_ms': 237344,
  'url': 'https://open.spotify.com/track/514joG57v4yKTsfQmz7stz',
  'song_added': '2026-07-31T12:48:02Z',
  'album_id': '0OAv7DCME2AV4q1KPO95HY',
  'artist_id': '3TVXtAsR1Inumwj472S9r4',
  'song_popularity': 84},
 {'song_id': '6sGIMrtIzQjdzNndVxe397',
  'song_name': 'So Easy (To Fall In Love)',
  'duration_ms': 169000,
  'url': 'https://open.spotify.com/track/6sGIMrtIzQjdzNndVxe397',
  'song_added': '2026-07-31T12:48:02Z',
  'album_id': '0l8zYqoUeBYg47Gmevq9HZ',
  'artist_id': '00x1fYSGhdqScXBRpSj3DW',
  'song_popularity': 92},
 {'song_id': '1rIKgCH4H52lrvDcz50hS8',
  'song_name': 'Lush Life',
  'duration_ms': 200646,
  'url': 'https://open.spotify.com/track/1rIKgCH4H52lrvDcz50hS8',
  'song_added': '2026-07-31T12:48:02Z',
  'album_id': '5YLRVHDVRw3QqWbeTGpC5B',
  'artist_id': '1Xylc3o4UrD53lo9CvFvVg',
  'song_popularity': 85},
 {'song_id': '70LcF31zb1H0PyJoS1Sx1r',
  'song_name': 'Creep',
  'duration_ms': 238640,
  'url': 'https://open.spotify.com/track/70LcF31zb1H0PyJoS1Sx1r',
  'song_added': '2026-07-31T12:48:02Z',
  'album_id': '3gBVdu4a1MMJVMy6vwPEb8',
  'artist_id': '4Z8W4fKeB5YxbusRsdQVPb',
  'song_popularity': 85},
 {'song_id': '5TFD2bmFKGhoCRbX61nXY5',
  'song_name': 'NUEVAYoL',
  'duration_ms': 183685,
  'url': 'https://open.spotify.com/track/5TFD2bmFKGhoCRbX61nXY5',
  'song_added': '2026-07-31T12:48:02Z',
  'album_id': '5K79FLRUCSysQnVESLcTdb',
  'artist_id': '4q3ewBCX7sLwd24euuV69X',
  'song_popularity': 87},
 {'song_id': '2lTm559tuIvatlT1u0JYG2',
  'song_name': 'BAILE INoLVIDABLE',
  'duration_ms': 367725,
  'url': 'https://open.spotify.com/track/2lTm559tuIvatlT1u0JYG2',
  'song_added': '2026-07-31T12:48:02Z',
  'album_id': '5K79FLRUCSysQnVESLcTdb',
  'artist_id': '4q3ewBCX7sLwd24euuV69X',
  'song_popularity': 88},
 {'song_id': '3d0WouFnFmr0K3kjeza3fF',
  'song_name': "Hips Don't Lie (feat. Wyclef Jean)",
  'duration_ms': 220360,
  'url': 'https://open.spotify.com/track/3d0WouFnFmr0K3kjeza3fF',
  'song_added': '2026-07-31T12:48:02Z',
  'album_id': '2cHhcN6iNLNXc7FByWBGi5',
  'artist_id': '0EmeFodog0BfCgMzAIvKQp, 7aBzpmFXB4WWpPl2F7RjBe',
  'song_popularity': 87},
 {'song_id': '2uXlHCUbq9OMUwx3hrk06o',
  'song_name': 'Riptide',
  'duration_ms': 204280,
  'url': 'https://open.spotify.com/track/2uXlHCUbq9OMUwx3hrk06o',
  'song_added': '2026-07-31T12:48:02Z',
  'album_id': '2biVG6BYnVVSwLYd1OjbPT',
  'artist_id': '10exVja0key0uqUkk6LJRT',
  'song_popularity': 89},
 {'song_id': '1zi7xx7UVEFkmKfv06H8x0',
  'song_name': 'One Dance',
  'duration_ms': 173986,
  'url': 'https://open.spotify.com/track/1zi7xx7UVEFkmKfv06H8x0',
  'song_added': '2026-07-31T12:48:02Z',
  'album_id': '40GMAhriYJRO1rsY4YdrZb',
  'artist_id': '3TVXtAsR1Inumwj472S9r4, 3tVQdUvClmAT7URs9V3rsp, 6TK7fjRPdy2GW2pJzNF23L',
  'song_popularity': 95},
 {'song_id': '3C0nOe05EIt1390bVABLyN',
  'song_name': 'On The Floor',
  'duration_ms': 284866,
  'url': 'https://open.spotify.com/track/3C0nOe05EIt1390bVABLyN',
  'song_added': '2026-07-31T12:48:02Z',
  'album_id': '3sysiYphqNRQw7VKLCg1yE',
  'artist_id': '2DlGxzQSjYe5N6G9nkYghR, 0TnOYISbd1XYRBk9myaseg',
  'song_popularity': 90}]

In [15]:
import pandas as pd

album_df = pd.DataFrame.from_dict(album_list)
album_df

,album_id,name,release_date,total_tracks,url,artist_name
0,2eeufspLkAubwTJfOGSrI8,Dai Dai,2026-05-14,1,https://open.spotify.com/album/2eeufspLkAubwTJ...,"Shakira, Burna Boy"
1,5cxMa6oLINJzmZ8lF7wWQN,Believe,2012-01-01,13,https://open.spotify.com/album/5cxMa6oLINJzmZ8...,Justin Bieber
2,1x159B5VzbDWAGBik5cr1z,hate that i made you love me,2026-05-29,1,https://open.spotify.com/album/1x159B5VzbDWAGB...,Ariana Grande
3,3ukkRHDHbN8tNRPKsGZR1h,ARIRANG,2026-03-20,14,https://open.spotify.com/album/3ukkRHDHbN8tNRP...,BTS
4,2jX6yKrWw9bY7JAYHhhtqZ,Sweet Boy,2024-04-05,16,https://open.spotify.com/album/2jX6yKrWw9bY7JA...,Malcolm Todd
5,2ANVost0y2y52ema1E9xAZ,Thriller,1982-11-30,9,https://open.spotify.com/album/2ANVost0y2y52em...,Michael Jackson
6,3ybCwWDhYDt2GYSCYFiF83,Animal,2026-07-24,2,https://open.spotify.com/album/3ybCwWDhYDt2GYS...,KATSEYE
7,05jbNkYoEQdjVDHEHtg1gY,"Don't Forget About Me, Demos",2018-10-16,8,https://open.spotify.com/album/05jbNkYoEQdjVDH...,Dominic Fike
8,7Cdqksm4yTfiq0EfKPa86M,Self Aware,2026-02-15,1,https://open.spotify.com/album/7Cdqksm4yTfiq0E...,Temper City
9,1VW1MFNstaJuygaoTPkdCk,(What's The Story) Morning Glory? [Remastered],1995-10-02,40,https://open.spotify.com/album/1VW1MFNstaJuyga...,Oasis
10,2UG6T6f0Qc9SaBCIcaviLM,Teenage Dream,2010-01-01,12,https://open.spotify.com/album/2UG6T6f0Qc9SaBC...,Katy Perry
11,18qJgKH8dyYe2RRp6TbnNY,you seem pretty sad for a girl so in love,2026-06-11,13,https://open.spotify.com/album/18qJgKH8dyYe2RR...,Olivia Rodrigo
12,7mvXPtV4jvA1hp5Wx2FAJA,I Barely Know Her,2025-08-22,10,https://open.spotify.com/album/7mvXPtV4jvA1hp5...,sombr
13,3WZZF72ihlKPZBS4zSsNHl,you seem pretty sad for a girl so in love,2026-06-12,13,https://open.spotify.com/album/3WZZF72ihlKPZBS...,Olivia Rodrigo
14,4UMjBXcRqIgMZ1XumU2x5T,Dizzy up the Girl,1998,13,https://open.spotify.com/album/4UMjBXcRqIgMZ1X...,The Goo Goo Dolls
15,6nrtxtgaD9zSYBl9APvOCH,Dandelion,2026-04-10,18,https://open.spotify.com/album/6nrtxtgaD9zSYBl...,Ella Langley
16,18qJgKH8dyYe2RRp6TbnNY,you seem pretty sad for a girl so in love,2026-06-11,13,https://open.spotify.com/album/18qJgKH8dyYe2RR...,Olivia Rodrigo
17,4JDXBZdRPId4devseaAOKH,DECIDE,2022-09-16,13,https://open.spotify.com/album/4JDXBZdRPId4dev...,Djo
18,2ANVost0y2y52ema1E9xAZ,Thriller,1982-11-30,9,https://open.spotify.com/album/2ANVost0y2y52em...,Michael Jackson
19,2MHUaRi9OCyTN02SoyRRBJ,MAYHEM,2025-03-07,14,https://open.spotify.com/album/2MHUaRi9OCyTN02...,Lady Gaga
20,0l8zYqoUeBYg47Gmevq9HZ,The Art of Loving,2025-09-26,12,https://open.spotify.com/album/0l8zYqoUeBYg47G...,Olivia Dean
21,1ne2D0NxoGyZd31gAM4HNd,Illuminate,2017-04-20,13,https://open.spotify.com/album/1ne2D0NxoGyZd31...,Shawn Mendes
22,1uE3dRPe3SrGdNhd1nWlSa,Bird's Eye,2024-08-09,11,https://open.spotify.com/album/1uE3dRPe3SrGdNh...,Ravyn Lenae
23,4a6NzYL1YHRUgx9e3YZI6I,The Life of a Showgirl,2025-10-03,12,https://open.spotify.com/album/4a6NzYL1YHRUgx9...,Taylor Swift
24,5K79FLRUCSysQnVESLcTdb,DeBÍ TiRAR MáS FOToS,2025-01-05,17,https://open.spotify.com/album/5K79FLRUCSysQnV...,Bad Bunny
25,4xkM0BwLM9H2IUcbYzpcBI,I Love You.,2013-04-22,11,https://open.spotify.com/album/4xkM0BwLM9H2IUc...,The Neighbourhood
26,1eCGY9WJpYgtaFh1Lk2KNo,"You'll Be Alright, Kid (Chapter 1)",2024-09-26,11,https://open.spotify.com/album/1eCGY9WJpYgtaFh...,Alex Warren
27,5ZX3Zdp20YCGI4ruAfZlMj,Jamaican (Bam Bam),2025-11-07,1,https://open.spotify.com/album/5ZX3Zdp20YCGI4r...,"HUGEL, SOLTO (FR)"
28,5W9OT0a5iZlBr83a9WMKFY,Synchronicity (Remastered 2003),1983-06-17,11,https://open.spotify.com/album/5W9OT0a5iZlBr83...,The Police
29,4piJq7R3gjUOxnYs6lDCTg,Hot Fuss,2004,12,https://open.spotify.com/album/4piJq7R3gjUOxnY...,The Killers
30,25hlG9lEbc2ARvZXY4ZDhv,Sesi Potret,2026-01-29,1,https://open.spotify.com/album/25hlG9lEbc2ARvZ...,"eńau, Ari Lesmana"
31,7vI4iTxDmgEN63liQHPEX1,The Romantic,2026-02-27,9,https://open.spotify.com/album/7vI4iTxDmgEN63l...,Bruno Mars
32,7aJuG4TFXa2hmE4z1yxc3n,HIT ME HARD AND SOFT,2024-05-17,10,https://open.spotify.com/album/7aJuG4TFXa2hmE4...,Billie Eilish
33,6f6tko6NWoH00cyFOl4VYQ,The Divine Feminine,2016-09-16,10,https://open.spotify.com/album/6f6tko6NWoH00cy...,Mac Miller
34,1FZKIm3JVDCxTchXDo5jOV,Harry Styles,2017-05-12,10,https://open.spotify.com/album/1FZKIm3JVDCxTch...,Harry Styles
35,58vZavXqh1P5uoTXteudWl,"At The Beach, In Every Life",2025-04-25,12,https://open.spotify.com/album/58vZavXqh1P5uoT...,Gigi Perez
36,58ufpQsJ1DS5kq4hhzQDiI,Unorthodox Jukebox,2012-12-07,10,https://open.spotify.com/album/58ufpQsJ1DS5kq4...,Bruno Mars
37,1lKquzZlhL5AWMHTeGej4M,CUARTO AZUL,2025-05-29,19,https://open.spotify.com/album/1lKquzZlhL5AWMH...,Aitana
38,24f1GFXCkViGoRpmGqlSSl,The Boy Who Played the Harp,2025-10-23,10,https://open.spotify.com/album/24f1GFXCkViGoRp...,Dave
39,6KFq3hJB6JnNvDbEHRvPoK,Dracula (Remix),2026-02-06,2,https://open.spotify.com/album/6KFq3hJB6JnNvDb...,"Tame Impala, JENNIE"
40,0OAv7DCME2AV4q1KPO95HY,ICEMAN,2026-05-15,18,https://open.spotify.com/album/0OAv7DCME2AV4q1...,Drake
41,0l8zYqoUeBYg47Gmevq9HZ,The Art of Loving,2025-09-26,12,https://open.spotify.com/album/0l8zYqoUeBYg47G...,Olivia Dean
42,5YLRVHDVRw3QqWbeTGpC5B,So Good,2017-03-17,15,https://open.spotify.com/album/5YLRVHDVRw3QqWb...,Zara Larsson
43,3gBVdu4a1MMJVMy6vwPEb8,Pablo Honey,1993-02-22,12,https://open.spotify.com/album/3gBVdu4a1MMJVMy...,Radiohead
44,5K79FLRUCSysQnVESLcTdb,DeBÍ TiRAR MáS FOToS,2025-01-05,17,https://open.spotify.com/album/5K79FLRUCSysQnV...,Bad Bunny
45,5K79FLRUCSysQnVESLcTdb,DeBÍ TiRAR MáS FOToS,2025-01-05,17,https://open.spotify.com/album/5K79FLRUCSysQnV...,Bad Bunny
46,2cHhcN6iNLNXc7FByWBGi5,"Oral Fixation, Vol. 2 (Expanded Edition)",2005-11-28,16,https://open.spotify.com/album/2cHhcN6iNLNXc7F...,Shakira
47,2biVG6BYnVVSwLYd1OjbPT,Dream Your Life Away (Deluxe Edition),2014-08-05,20,https://open.spotify.com/album/2biVG6BYnVVSwLY...,Vance Joy
48,40GMAhriYJRO1rsY4YdrZb,Views,2016-05-06,20,https://open.spotify.com/album/40GMAhriYJRO1rs...,Drake
49,3sysiYphqNRQw7VKLCg1yE,Love?,2011-04-29,17,https://open.spotify.com/album/3sysiYphqNRQw7V...,Jennifer Lopez

In [16]:
album_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 6 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   album_id      50 non-null     str
 1   name          50 non-null     str
 2   release_date  50 non-null     str
 3   total_tracks  50 non-null     int64
 4   url           50 non-null     str
 5   artist_name   50 non-null     str
dtypes: int64(1), str(5)
memory usage: 8.0 KB

In [17]:
album_df = album_df.drop_duplicates(subset=['album_id'])

In [18]:
artist_df = pd.DataFrame.from_dict(artist_list)
artist_df

,artist_id,artist_name,external_url
0,0EmeFodog0BfCgMzAIvKQp,Shakira,https://api.spotify.com/v1/artists/0EmeFodog0B...
1,3wcj11K77LjEY1PkEazffa,Burna Boy,https://api.spotify.com/v1/artists/3wcj11K77Lj...
2,1uNFoZAHBGtllmzznpCI3s,Justin Bieber,https://api.spotify.com/v1/artists/1uNFoZAHBGt...
3,0hCNtLu0JehylgoiP8L4Gh,Nicki Minaj,https://api.spotify.com/v1/artists/0hCNtLu0Jeh...
4,66CXWjxzNUsdJxJ2JdwvnR,Ariana Grande,https://api.spotify.com/v1/artists/66CXWjxzNUs...
...,...,...,...
57,3TVXtAsR1Inumwj472S9r4,Drake,https://api.spotify.com/v1/artists/3TVXtAsR1In...
58,3tVQdUvClmAT7URs9V3rsp,Wizkid,https://api.spotify.com/v1/artists/3tVQdUvClmA...
59,6TK7fjRPdy2GW2pJzNF23L,Kyla,https://api.spotify.com/v1/artists/6TK7fjRPdy2...
60,2DlGxzQSjYe5N6G9nkYghR,Jennifer Lopez,https://api.spotify.com/v1/artists/2DlGxzQSjYe...
61,0TnOYISbd1XYRBk9myaseg,Pitbull,https://api.spotify.com/v1/artists/0TnOYISbd1X...

In [19]:
artist_df = artist_df.drop_duplicates(subset=['artist_id'])

In [20]:
song_df = pd.DataFrame.from_dict(song_list)
song_df

,song_id,song_name,duration_ms,url,song_added,album_id,artist_id,song_popularity
0,0kosUz0jePvjiz4ctmR6wL,Dai Dai,223448,https://open.spotify.com/track/0kosUz0jePvjiz4...,2026-07-31T12:48:02Z,2eeufspLkAubwTJfOGSrI8,"0EmeFodog0BfCgMzAIvKQp, 3wcj11K77LjEY1PkEazffa",81
1,6QFCMUUq1T2Vf5sFUXcuQ7,Beauty And A Beat,227986,https://open.spotify.com/track/6QFCMUUq1T2Vf5s...,2026-07-31T12:48:02Z,5cxMa6oLINJzmZ8lF7wWQN,"1uNFoZAHBGtllmzznpCI3s, 0hCNtLu0JehylgoiP8L4Gh",91
2,20jbSiX29FDX4oQxBXyUEi,hate that i made you love me,197949,https://open.spotify.com/track/20jbSiX29FDX4oQ...,2026-07-31T12:48:02Z,1x159B5VzbDWAGBik5cr1z,66CXWjxzNUsdJxJ2JdwvnR,91
3,68lbSrXDORS51pmyjZv712,SWIM,159007,https://open.spotify.com/track/68lbSrXDORS51pm...,2026-07-31T12:48:02Z,3ukkRHDHbN8tNRPKsGZR1h,3Nrfpe0tUJi4K4DXYWgMUX,87
4,0eAuGrXyGFYwur9ARUe7LJ,Earrings,151500,https://open.spotify.com/track/0eAuGrXyGFYwur9...,2026-07-31T12:48:02Z,2jX6yKrWw9bY7JAYHhhtqZ,7eKkW1zo5uzW8kUntiiBvz,90
5,7J1uxwnxfQLu4APicE5Rnj,Billie Jean,293802,https://open.spotify.com/track/7J1uxwnxfQLu4AP...,2026-07-31T12:48:02Z,2ANVost0y2y52ema1E9xAZ,3fMbdgg4jU18AjLCKBhRSm,93
6,3ouNEk0tv5TTi8VWMe1xbX,Animal,158494,https://open.spotify.com/track/3ouNEk0tv5TTi8V...,2026-07-31T12:48:02Z,3ybCwWDhYDt2GYSCYFiF83,3c0gDdb9lhnHGFtP4prQpn,88
7,7yNf9YjeO5JXUE3JEBgnYc,Babydoll,97960,https://open.spotify.com/track/7yNf9YjeO5JXUE3...,2026-07-31T12:48:02Z,05jbNkYoEQdjVDHEHtg1gY,6USv9qhCn6zfxlBQIYJ9qs,95
8,4qW3BbQAwZsrnu8a3ZRdyT,Self Aware,180740,https://open.spotify.com/track/4qW3BbQAwZsrnu8...,2026-07-31T12:48:02Z,7Cdqksm4yTfiq0EfKPa86M,5mHUmlJWkcoOk1NbjfrXWz,79
9,5qqabIl2vWzo9ApSC317sa,Wonderwall - Remastered,258773,https://open.spotify.com/track/5qqabIl2vWzo9Ap...,2026-07-31T12:48:02Z,1VW1MFNstaJuygaoTPkdCk,2DaxqgrOhkeH0fpeiQq2f4,93
10,2009X8GyWTqyxIdzAEYW6N,The One That Got Away,227333,https://open.spotify.com/track/2009X8GyWTqyxId...,2026-07-31T12:48:02Z,2UG6T6f0Qc9SaBCIcaviLM,6jJ0s89eD6GaHleKKya26X,75
11,49j6SvuvWfbEKZKzsHCdLJ,stupid song,209680,https://open.spotify.com/track/49j6SvuvWfbEKZK...,2026-07-31T12:48:02Z,18qJgKH8dyYe2RRp6TbnNY,1McMsnEElThX1knmY4oliG,93
12,7qjZnBKE73H4Oxkopwulqe,back to friends,199032,https://open.spotify.com/track/7qjZnBKE73H4Oxk...,2026-07-31T12:48:02Z,7mvXPtV4jvA1hp5Wx2FAJA,4G9NDjRyZFDlJKMRL8hx3S,93
13,55pBIZO1cqoldeqpp5WR7H,the cure,297090,https://open.spotify.com/track/55pBIZO1cqoldeq...,2026-07-31T12:48:02Z,3WZZF72ihlKPZBS4zSsNHl,1McMsnEElThX1knmY4oliG,89
14,6Qyc6fS4DsZjB2mRW9DsQs,Iris,289533,https://open.spotify.com/track/6Qyc6fS4DsZjB2m...,2026-07-31T12:48:02Z,4UMjBXcRqIgMZ1XumU2x5T,2sil8z5kiy4r76CRTXxBCA,85
15,7scFxt9VhL4FJwuPSfRlfN,Choosin' Texas,231746,https://open.spotify.com/track/7scFxt9VhL4FJwu...,2026-07-31T12:48:02Z,6nrtxtgaD9zSYBl9APvOCH,6BRxQ8cD3eqnrVj6WKDok8,87
16,3fRCAPMMZ8l8P9YKI6OCzD,drop dead,224998,https://open.spotify.com/track/3fRCAPMMZ8l8P9Y...,2026-07-31T12:48:02Z,18qJgKH8dyYe2RRp6TbnNY,1McMsnEElThX1knmY4oliG,90
17,3qhlB30KknSejmIvZZLjOD,End of Beginning,159245,https://open.spotify.com/track/3qhlB30KknSejmI...,2026-07-31T12:48:02Z,4JDXBZdRPId4devseaAOKH,5p9HO3XC5P3BLxJs5Mtrhm,93
18,3BovdzfaX4jb5KFQwoPfAw,Beat It,258296,https://open.spotify.com/track/3BovdzfaX4jb5KF...,2026-07-31T12:48:02Z,2ANVost0y2y52ema1E9xAZ,3fMbdgg4jU18AjLCKBhRSm,80
19,7so0lgd0zP2Sbgs2d7a1SZ,Die With A Smile,251667,https://open.spotify.com/track/7so0lgd0zP2Sbgs...,2026-07-31T12:48:02Z,2MHUaRi9OCyTN02SoyRRBJ,"1HY2Jd0NmPuamShAr6KMms, 0du5cEVh5yTK9QJze8zA0C",78
20,0mYXRQpTGjaLJt1l9MY4ps,Man I Need,184000,https://open.spotify.com/track/0mYXRQpTGjaLJt1...,2026-07-31T12:48:02Z,0l8zYqoUeBYg47Gmevq9HZ,00x1fYSGhdqScXBRpSj3DW,91
21,3QGsuHI8jO1Rx4JWLUh9jd,Treat You Better,187973,https://open.spotify.com/track/3QGsuHI8jO1Rx4J...,2026-07-31T12:48:02Z,1ne2D0NxoGyZd31gAM4HNd,7n2wHs1TKAczGzO7Dd2rGr,77
22,4WFgvKVfEhb3IUAFGrutTR,Love Me Not,213466,https://open.spotify.com/track/4WFgvKVfEhb3IUA...,2026-07-31T12:48:02Z,1uE3dRPe3SrGdNhd1nWlSa,5RTLRtXjbXI2lSXc6jxlAz,94
23,53iuhJlwXhSER5J2IYYv1W,The Fate of Ophelia,226073,https://open.spotify.com/track/53iuhJlwXhSER5J...,2026-07-31T12:48:02Z,4a6NzYL1YHRUgx9e3YZI6I,06HL4z0CvFAxyc27GXpf02,83
24,3sK8wGT43QFpWrvNQsrQya,DtMF,237117,https://open.spotify.com/track/3sK8wGT43QFpWrv...,2026-07-31T12:48:02Z,5K79FLRUCSysQnVESLcTdb,4q3ewBCX7sLwd24euuV69X,91
25,2QjOHCTQ1Jl3zawyYOpxh6,Sweater Weather,240400,https://open.spotify.com/track/2QjOHCTQ1Jl3zaw...,2026-07-31T12:48:02Z,4xkM0BwLM9H2IUcbYzpcBI,77SW9BnxLY8rJ0RciFqkHh,92
26,2RkZ5LkEzeHGRsmDqKwmaJ,Ordinary,186964,https://open.spotify.com/track/2RkZ5LkEzeHGRsm...,2026-07-31T12:48:02Z,1eCGY9WJpYgtaFh1Lk2KNo,0fTSzq9jAh4c36UVb4V7CB,81
27,7e4zDInS6tA2jwzphvs2Ay,Jamaican (Bam Bam),156393,https://open.spotify.com/track/7e4zDInS6tA2jwz...,2026-07-31T12:48:02Z,5ZX3Zdp20YCGI4ruAfZlMj,"5PlfkPxwCpRRWQJBxCa0By, 0F3tUZeb9dLNEpxCpzEBQt",79
28,1JSTJqkT5qHq8MDJnJbRE1,Every Breath You Take,253920,https://open.spotify.com/track/1JSTJqkT5qHq8MD...,2026-07-31T12:48:02Z,5W9OT0a5iZlBr83a9WMKFY,5NGO30tJxFlKixkPSgXcFE,94
29,003vvx7Niy0yvhvHt4a68B,Mr. Brightside,222973,https://open.spotify.com/track/003vvx7Niy0yvhv...,2026-07-31T12:48:02Z,4piJq7R3gjUOxnYs6lDCTg,0C0XlULifJtAgn6ZNCW2eu,86
30,4xoY4lZNoTjEuHsSmhgF1G,Sesi Potret,243000,https://open.spotify.com/track/4xoY4lZNoTjEuHs...,2026-07-31T12:48:02Z,25hlG9lEbc2ARvZXY4ZDhv,"0agUNq8PH1QSgm88EuhM1u, 3MMDw11m6HJrXlGOE3honc",92
31,5y2ijHECwFYWqcAHKTZgzD,Risk It All,204068,https://open.spotify.com/track/5y2ijHECwFYWqcA...,2026-07-31T12:48:02Z,7vI4iTxDmgEN63liQHPEX1,0du5cEVh5yTK9QJze8zA0C,89
32,6dOtVTDdiauQNBQEDOtlAB,BIRDS OF A FEATHER,210373,https://open.spotify.com/track/6dOtVTDdiauQNBQ...,2026-07-31T12:48:02Z,7aJuG4TFXa2hmE4z1yxc3n,6qqNVTkY8uBg9cP3Jd7DAH,76
33,2lpygKqzPFtItQ4ss3cgfb,Cinderella (feat. Ty Dolla $ign),480186,https://open.spotify.com/track/2lpygKqzPFtItQ4...,2026-07-31T12:48:02Z,6f6tko6NWoH00cyFOl4VYQ,"4LLpKhyESsyAXpc4laK94U, 7c0XG5cIJTrrAgEC3ULPiq",78
34,5Ohxk2dO5COHF1krpoPigN,Sign of the Times,340706,https://open.spotify.com/track/5Ohxk2dO5COHF1k...,2026-07-31T12:48:02Z,1FZKIm3JVDCxTchXDo5jOV,6KImCVD70vtIoJWnq6nGn3,94
35,21IYMdzTrzSe191Cy5eMap,Sailor Song,211978,https://open.spotify.com/track/21IYMdzTrzSe191...,2026-07-31T12:48:02Z,58vZavXqh1P5uoTXteudWl,1iCnM8foFssWlPRLfAbIwo,83
36,3w3y8KPTfNeOKPiqUTakBh,Locked out of Heaven,233478,https://open.spotify.com/track/3w3y8KPTfNeOKPi...,2026-07-31T12:48:02Z,58ufpQsJ1DS5kq4hhzQDiI,0du5cEVh5yTK9QJze8zA0C,90
37,6hpuesKPNa3WhV48O7Fa47,SUPERESTRELLA,183529,https://open.spotify.com/track/6hpuesKPNa3WhV4...,2026-07-31T12:48:02Z,1lKquzZlhL5AWMHTeGej4M,7eLcDZDYHXZCebtQmVFL25,95
38,3oTuTpF1F3A7rEC6RKsMRz,Raindance (feat. Tems),219743,https://open.spotify.com/track/3oTuTpF1F3A7rEC...,2026-07-31T12:48:02Z,24f1GFXCkViGoRpmGqlSSl,"6Ip8FS7vWT1uKkJSweANQK, 687cZJR45JO7jhk1LHIbgq",77
39,5yvVYFDUpbnjcnRBgjwTzM,Dracula - JENNIE Remix,209720,https://open.spotify.com/track/5yvVYFDUpbnjcnR...,2026-07-31T12:48:02Z,6KFq3hJB6JnNvDbEHRvPoK,"5INjqkS1o8h1imAzPqGZBb, 250b0Wlc5Vk0CoUsaCY84M",77
40,514joG57v4yKTsfQmz7stz,Janice STFU,237344,https://open.spotify.com/track/514joG57v4yKTsf...,2026-07-31T12:48:02Z,0OAv7DCME2AV4q1KPO95HY,3TVXtAsR1Inumwj472S9r4,84
41,6sGIMrtIzQjdzNndVxe397,So Easy (To Fall In Love),169000,https://open.spotify.com/track/6sGIMrtIzQjdzNn...,2026-07-31T12:48:02Z,0l8zYqoUeBYg47Gmevq9HZ,00x1fYSGhdqScXBRpSj3DW,92
42,1rIKgCH4H52lrvDcz50hS8,Lush Life,200646,https://open.spotify.com/track/1rIKgCH4H52lrvD...,2026-07-31T12:48:02Z,5YLRVHDVRw3QqWbeTGpC5B,1Xylc3o4UrD53lo9CvFvVg,85
43,70LcF31zb1H0PyJoS1Sx1r,Creep,238640,https://open.spotify.com/track/70LcF31zb1H0PyJ...,2026-07-31T12:48:02Z,3gBVdu4a1MMJVMy6vwPEb8,4Z8W4fKeB5YxbusRsdQVPb,85
44,5TFD2bmFKGhoCRbX61nXY5,NUEVAYoL,183685,https://open.spotify.com/track/5TFD2bmFKGhoCRb...,2026-07-31T12:48:02Z,5K79FLRUCSysQnVESLcTdb,4q3ewBCX7sLwd24euuV69X,87
45,2lTm559tuIvatlT1u0JYG2,BAILE INoLVIDABLE,367725,https://open.spotify.com/track/2lTm559tuIvatlT...,2026-07-31T12:48:02Z,5K79FLRUCSysQnVESLcTdb,4q3ewBCX7sLwd24euuV69X,88
46,3d0WouFnFmr0K3kjeza3fF,Hips Don't Lie (feat. Wyclef Jean),220360,https://open.spotify.com/track/3d0WouFnFmr0K3k...,2026-07-31T12:48:02Z,2cHhcN6iNLNXc7FByWBGi5,"0EmeFodog0BfCgMzAIvKQp, 7aBzpmFXB4WWpPl2F7RjBe",87
47,2uXlHCUbq9OMUwx3hrk06o,Riptide,204280,https://open.spotify.com/track/2uXlHCUbq9OMUwx...,2026-07-31T12:48:02Z,2biVG6BYnVVSwLYd1OjbPT,10exVja0key0uqUkk6LJRT,89
48,1zi7xx7UVEFkmKfv06H8x0,One Dance,173986,https://open.spotify.com/track/1zi7xx7UVEFkmKf...,2026-07-31T12:48:02Z,40GMAhriYJRO1rsY4YdrZb,"3TVXtAsR1Inumwj472S9r4, 3tVQdUvClmAT7URs9V3rsp...",95
49,3C0nOe05EIt1390bVABLyN,On The Floor,284866,https://open.spotify.com/track/3C0nOe05EIt1390...,2026-07-31T12:48:02Z,3sysiYphqNRQw7VKLCg1yE,"2DlGxzQSjYe5N6G9nkYghR, 0TnOYISbd1XYRBk9myaseg",90

In [21]:
song_df = song_df.drop_duplicates(subset=['song_id'])

In [22]:
#Now we have album_df, artist_df, song_df
album_df.info()

<class 'pandas.DataFrame'>
Index: 45 entries, 0 to 49
Data columns (total 6 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   album_id      45 non-null     str
 1   name          45 non-null     str
 2   release_date  45 non-null     str
 3   total_tracks  45 non-null     int64
 4   url           45 non-null     str
 5   artist_name   45 non-null     str
dtypes: int64(1), str(5)
memory usage: 7.4 KB

In [23]:
album_df['release_date'] = pd.to_datetime(
    album_df['release_date'],
    format='mixed'
)

In [24]:
album_df.info()

<class 'pandas.DataFrame'>
Index: 45 entries, 0 to 49
Data columns (total 6 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   album_id      45 non-null     str
 1   name          45 non-null     str
 2   release_date  45 non-null     datetime64[us]
 3   total_tracks  45 non-null     int64
 4   url           45 non-null     str
 5   artist_name   45 non-null     str
dtypes: datetime64[us](1), int64(1), str(4)
memory usage: 7.0 KB

In [25]:
album_df

,album_id,name,release_date,total_tracks,url,artist_name
0,2eeufspLkAubwTJfOGSrI8,Dai Dai,2026-05-14,1,https://open.spotify.com/album/2eeufspLkAubwTJ...,"Shakira, Burna Boy"
1,5cxMa6oLINJzmZ8lF7wWQN,Believe,2012-01-01,13,https://open.spotify.com/album/5cxMa6oLINJzmZ8...,Justin Bieber
2,1x159B5VzbDWAGBik5cr1z,hate that i made you love me,2026-05-29,1,https://open.spotify.com/album/1x159B5VzbDWAGB...,Ariana Grande
3,3ukkRHDHbN8tNRPKsGZR1h,ARIRANG,2026-03-20,14,https://open.spotify.com/album/3ukkRHDHbN8tNRP...,BTS
4,2jX6yKrWw9bY7JAYHhhtqZ,Sweet Boy,2024-04-05,16,https://open.spotify.com/album/2jX6yKrWw9bY7JA...,Malcolm Todd
5,2ANVost0y2y52ema1E9xAZ,Thriller,1982-11-30,9,https://open.spotify.com/album/2ANVost0y2y52em...,Michael Jackson
6,3ybCwWDhYDt2GYSCYFiF83,Animal,2026-07-24,2,https://open.spotify.com/album/3ybCwWDhYDt2GYS...,KATSEYE
7,05jbNkYoEQdjVDHEHtg1gY,"Don't Forget About Me, Demos",2018-10-16,8,https://open.spotify.com/album/05jbNkYoEQdjVDH...,Dominic Fike
8,7Cdqksm4yTfiq0EfKPa86M,Self Aware,2026-02-15,1,https://open.spotify.com/album/7Cdqksm4yTfiq0E...,Temper City
9,1VW1MFNstaJuygaoTPkdCk,(What's The Story) Morning Glory? [Remastered],1995-10-02,40,https://open.spotify.com/album/1VW1MFNstaJuyga...,Oasis
10,2UG6T6f0Qc9SaBCIcaviLM,Teenage Dream,2010-01-01,12,https://open.spotify.com/album/2UG6T6f0Qc9SaBC...,Katy Perry
11,18qJgKH8dyYe2RRp6TbnNY,you seem pretty sad for a girl so in love,2026-06-11,13,https://open.spotify.com/album/18qJgKH8dyYe2RR...,Olivia Rodrigo
12,7mvXPtV4jvA1hp5Wx2FAJA,I Barely Know Her,2025-08-22,10,https://open.spotify.com/album/7mvXPtV4jvA1hp5...,sombr
13,3WZZF72ihlKPZBS4zSsNHl,you seem pretty sad for a girl so in love,2026-06-12,13,https://open.spotify.com/album/3WZZF72ihlKPZBS...,Olivia Rodrigo
14,4UMjBXcRqIgMZ1XumU2x5T,Dizzy up the Girl,1998-01-01,13,https://open.spotify.com/album/4UMjBXcRqIgMZ1X...,The Goo Goo Dolls
15,6nrtxtgaD9zSYBl9APvOCH,Dandelion,2026-04-10,18,https://open.spotify.com/album/6nrtxtgaD9zSYBl...,Ella Langley
17,4JDXBZdRPId4devseaAOKH,DECIDE,2022-09-16,13,https://open.spotify.com/album/4JDXBZdRPId4dev...,Djo
19,2MHUaRi9OCyTN02SoyRRBJ,MAYHEM,2025-03-07,14,https://open.spotify.com/album/2MHUaRi9OCyTN02...,Lady Gaga
20,0l8zYqoUeBYg47Gmevq9HZ,The Art of Loving,2025-09-26,12,https://open.spotify.com/album/0l8zYqoUeBYg47G...,Olivia Dean
21,1ne2D0NxoGyZd31gAM4HNd,Illuminate,2017-04-20,13,https://open.spotify.com/album/1ne2D0NxoGyZd31...,Shawn Mendes
22,1uE3dRPe3SrGdNhd1nWlSa,Bird's Eye,2024-08-09,11,https://open.spotify.com/album/1uE3dRPe3SrGdNh...,Ravyn Lenae
23,4a6NzYL1YHRUgx9e3YZI6I,The Life of a Showgirl,2025-10-03,12,https://open.spotify.com/album/4a6NzYL1YHRUgx9...,Taylor Swift
24,5K79FLRUCSysQnVESLcTdb,DeBÍ TiRAR MáS FOToS,2025-01-05,17,https://open.spotify.com/album/5K79FLRUCSysQnV...,Bad Bunny
25,4xkM0BwLM9H2IUcbYzpcBI,I Love You.,2013-04-22,11,https://open.spotify.com/album/4xkM0BwLM9H2IUc...,The Neighbourhood
26,1eCGY9WJpYgtaFh1Lk2KNo,"You'll Be Alright, Kid (Chapter 1)",2024-09-26,11,https://open.spotify.com/album/1eCGY9WJpYgtaFh...,Alex Warren
27,5ZX3Zdp20YCGI4ruAfZlMj,Jamaican (Bam Bam),2025-11-07,1,https://open.spotify.com/album/5ZX3Zdp20YCGI4r...,"HUGEL, SOLTO (FR)"
28,5W9OT0a5iZlBr83a9WMKFY,Synchronicity (Remastered 2003),1983-06-17,11,https://open.spotify.com/album/5W9OT0a5iZlBr83...,The Police
29,4piJq7R3gjUOxnYs6lDCTg,Hot Fuss,2004-01-01,12,https://open.spotify.com/album/4piJq7R3gjUOxnY...,The Killers
30,25hlG9lEbc2ARvZXY4ZDhv,Sesi Potret,2026-01-29,1,https://open.spotify.com/album/25hlG9lEbc2ARvZ...,"eńau, Ari Lesmana"
31,7vI4iTxDmgEN63liQHPEX1,The Romantic,2026-02-27,9,https://open.spotify.com/album/7vI4iTxDmgEN63l...,Bruno Mars
32,7aJuG4TFXa2hmE4z1yxc3n,HIT ME HARD AND SOFT,2024-05-17,10,https://open.spotify.com/album/7aJuG4TFXa2hmE4...,Billie Eilish
33,6f6tko6NWoH00cyFOl4VYQ,The Divine Feminine,2016-09-16,10,https://open.spotify.com/album/6f6tko6NWoH00cy...,Mac Miller
34,1FZKIm3JVDCxTchXDo5jOV,Harry Styles,2017-05-12,10,https://open.spotify.com/album/1FZKIm3JVDCxTch...,Harry Styles
35,58vZavXqh1P5uoTXteudWl,"At The Beach, In Every Life",2025-04-25,12,https://open.spotify.com/album/58vZavXqh1P5uoT...,Gigi Perez
36,58ufpQsJ1DS5kq4hhzQDiI,Unorthodox Jukebox,2012-12-07,10,https://open.spotify.com/album/58ufpQsJ1DS5kq4...,Bruno Mars
37,1lKquzZlhL5AWMHTeGej4M,CUARTO AZUL,2025-05-29,19,https://open.spotify.com/album/1lKquzZlhL5AWMH...,Aitana
38,24f1GFXCkViGoRpmGqlSSl,The Boy Who Played the Harp,2025-10-23,10,https://open.spotify.com/album/24f1GFXCkViGoRp...,Dave
39,6KFq3hJB6JnNvDbEHRvPoK,Dracula (Remix),2026-02-06,2,https://open.spotify.com/album/6KFq3hJB6JnNvDb...,"Tame Impala, JENNIE"
40,0OAv7DCME2AV4q1KPO95HY,ICEMAN,2026-05-15,18,https://open.spotify.com/album/0OAv7DCME2AV4q1...,Drake
42,5YLRVHDVRw3QqWbeTGpC5B,So Good,2017-03-17,15,https://open.spotify.com/album/5YLRVHDVRw3QqWb...,Zara Larsson
43,3gBVdu4a1MMJVMy6vwPEb8,Pablo Honey,1993-02-22,12,https://open.spotify.com/album/3gBVdu4a1MMJVMy...,Radiohead
46,2cHhcN6iNLNXc7FByWBGi5,"Oral Fixation, Vol. 2 (Expanded Edition)",2005-11-28,16,https://open.spotify.com/album/2cHhcN6iNLNXc7F...,Shakira
47,2biVG6BYnVVSwLYd1OjbPT,Dream Your Life Away (Deluxe Edition),2014-08-05,20,https://open.spotify.com/album/2biVG6BYnVVSwLY...,Vance Joy
48,40GMAhriYJRO1rsY4YdrZb,Views,2016-05-06,20,https://open.spotify.com/album/40GMAhriYJRO1rs...,Drake
49,3sysiYphqNRQw7VKLCg1yE,Love?,2011-04-29,17,https://open.spotify.com/album/3sysiYphqNRQw7V...,Jennifer Lopez

In [26]:
song_df['song_added'] = pd.to_datetime(
    song_df['song_added'],
    format='mixed'
)

In [27]:
song_df

,song_id,song_name,duration_ms,url,song_added,album_id,artist_id,song_popularity
0,0kosUz0jePvjiz4ctmR6wL,Dai Dai,223448,https://open.spotify.com/track/0kosUz0jePvjiz4...,2026-07-31 12:48:02+00:00,2eeufspLkAubwTJfOGSrI8,"0EmeFodog0BfCgMzAIvKQp, 3wcj11K77LjEY1PkEazffa",81
1,6QFCMUUq1T2Vf5sFUXcuQ7,Beauty And A Beat,227986,https://open.spotify.com/track/6QFCMUUq1T2Vf5s...,2026-07-31 12:48:02+00:00,5cxMa6oLINJzmZ8lF7wWQN,"1uNFoZAHBGtllmzznpCI3s, 0hCNtLu0JehylgoiP8L4Gh",91
2,20jbSiX29FDX4oQxBXyUEi,hate that i made you love me,197949,https://open.spotify.com/track/20jbSiX29FDX4oQ...,2026-07-31 12:48:02+00:00,1x159B5VzbDWAGBik5cr1z,66CXWjxzNUsdJxJ2JdwvnR,91
3,68lbSrXDORS51pmyjZv712,SWIM,159007,https://open.spotify.com/track/68lbSrXDORS51pm...,2026-07-31 12:48:02+00:00,3ukkRHDHbN8tNRPKsGZR1h,3Nrfpe0tUJi4K4DXYWgMUX,87
4,0eAuGrXyGFYwur9ARUe7LJ,Earrings,151500,https://open.spotify.com/track/0eAuGrXyGFYwur9...,2026-07-31 12:48:02+00:00,2jX6yKrWw9bY7JAYHhhtqZ,7eKkW1zo5uzW8kUntiiBvz,90
5,7J1uxwnxfQLu4APicE5Rnj,Billie Jean,293802,https://open.spotify.com/track/7J1uxwnxfQLu4AP...,2026-07-31 12:48:02+00:00,2ANVost0y2y52ema1E9xAZ,3fMbdgg4jU18AjLCKBhRSm,93
6,3ouNEk0tv5TTi8VWMe1xbX,Animal,158494,https://open.spotify.com/track/3ouNEk0tv5TTi8V...,2026-07-31 12:48:02+00:00,3ybCwWDhYDt2GYSCYFiF83,3c0gDdb9lhnHGFtP4prQpn,88
7,7yNf9YjeO5JXUE3JEBgnYc,Babydoll,97960,https://open.spotify.com/track/7yNf9YjeO5JXUE3...,2026-07-31 12:48:02+00:00,05jbNkYoEQdjVDHEHtg1gY,6USv9qhCn6zfxlBQIYJ9qs,95
8,4qW3BbQAwZsrnu8a3ZRdyT,Self Aware,180740,https://open.spotify.com/track/4qW3BbQAwZsrnu8...,2026-07-31 12:48:02+00:00,7Cdqksm4yTfiq0EfKPa86M,5mHUmlJWkcoOk1NbjfrXWz,79
9,5qqabIl2vWzo9ApSC317sa,Wonderwall - Remastered,258773,https://open.spotify.com/track/5qqabIl2vWzo9Ap...,2026-07-31 12:48:02+00:00,1VW1MFNstaJuygaoTPkdCk,2DaxqgrOhkeH0fpeiQq2f4,93
10,2009X8GyWTqyxIdzAEYW6N,The One That Got Away,227333,https://open.spotify.com/track/2009X8GyWTqyxId...,2026-07-31 12:48:02+00:00,2UG6T6f0Qc9SaBCIcaviLM,6jJ0s89eD6GaHleKKya26X,75
11,49j6SvuvWfbEKZKzsHCdLJ,stupid song,209680,https://open.spotify.com/track/49j6SvuvWfbEKZK...,2026-07-31 12:48:02+00:00,18qJgKH8dyYe2RRp6TbnNY,1McMsnEElThX1knmY4oliG,93
12,7qjZnBKE73H4Oxkopwulqe,back to friends,199032,https://open.spotify.com/track/7qjZnBKE73H4Oxk...,2026-07-31 12:48:02+00:00,7mvXPtV4jvA1hp5Wx2FAJA,4G9NDjRyZFDlJKMRL8hx3S,93
13,55pBIZO1cqoldeqpp5WR7H,the cure,297090,https://open.spotify.com/track/55pBIZO1cqoldeq...,2026-07-31 12:48:02+00:00,3WZZF72ihlKPZBS4zSsNHl,1McMsnEElThX1knmY4oliG,89
14,6Qyc6fS4DsZjB2mRW9DsQs,Iris,289533,https://open.spotify.com/track/6Qyc6fS4DsZjB2m...,2026-07-31 12:48:02+00:00,4UMjBXcRqIgMZ1XumU2x5T,2sil8z5kiy4r76CRTXxBCA,85
15,7scFxt9VhL4FJwuPSfRlfN,Choosin' Texas,231746,https://open.spotify.com/track/7scFxt9VhL4FJwu...,2026-07-31 12:48:02+00:00,6nrtxtgaD9zSYBl9APvOCH,6BRxQ8cD3eqnrVj6WKDok8,87
16,3fRCAPMMZ8l8P9YKI6OCzD,drop dead,224998,https://open.spotify.com/track/3fRCAPMMZ8l8P9Y...,2026-07-31 12:48:02+00:00,18qJgKH8dyYe2RRp6TbnNY,1McMsnEElThX1knmY4oliG,90
17,3qhlB30KknSejmIvZZLjOD,End of Beginning,159245,https://open.spotify.com/track/3qhlB30KknSejmI...,2026-07-31 12:48:02+00:00,4JDXBZdRPId4devseaAOKH,5p9HO3XC5P3BLxJs5Mtrhm,93
18,3BovdzfaX4jb5KFQwoPfAw,Beat It,258296,https://open.spotify.com/track/3BovdzfaX4jb5KF...,2026-07-31 12:48:02+00:00,2ANVost0y2y52ema1E9xAZ,3fMbdgg4jU18AjLCKBhRSm,80
19,7so0lgd0zP2Sbgs2d7a1SZ,Die With A Smile,251667,https://open.spotify.com/track/7so0lgd0zP2Sbgs...,2026-07-31 12:48:02+00:00,2MHUaRi9OCyTN02SoyRRBJ,"1HY2Jd0NmPuamShAr6KMms, 0du5cEVh5yTK9QJze8zA0C",78
20,0mYXRQpTGjaLJt1l9MY4ps,Man I Need,184000,https://open.spotify.com/track/0mYXRQpTGjaLJt1...,2026-07-31 12:48:02+00:00,0l8zYqoUeBYg47Gmevq9HZ,00x1fYSGhdqScXBRpSj3DW,91
21,3QGsuHI8jO1Rx4JWLUh9jd,Treat You Better,187973,https://open.spotify.com/track/3QGsuHI8jO1Rx4J...,2026-07-31 12:48:02+00:00,1ne2D0NxoGyZd31gAM4HNd,7n2wHs1TKAczGzO7Dd2rGr,77
22,4WFgvKVfEhb3IUAFGrutTR,Love Me Not,213466,https://open.spotify.com/track/4WFgvKVfEhb3IUA...,2026-07-31 12:48:02+00:00,1uE3dRPe3SrGdNhd1nWlSa,5RTLRtXjbXI2lSXc6jxlAz,94
23,53iuhJlwXhSER5J2IYYv1W,The Fate of Ophelia,226073,https://open.spotify.com/track/53iuhJlwXhSER5J...,2026-07-31 12:48:02+00:00,4a6NzYL1YHRUgx9e3YZI6I,06HL4z0CvFAxyc27GXpf02,83
24,3sK8wGT43QFpWrvNQsrQya,DtMF,237117,https://open.spotify.com/track/3sK8wGT43QFpWrv...,2026-07-31 12:48:02+00:00,5K79FLRUCSysQnVESLcTdb,4q3ewBCX7sLwd24euuV69X,91
25,2QjOHCTQ1Jl3zawyYOpxh6,Sweater Weather,240400,https://open.spotify.com/track/2QjOHCTQ1Jl3zaw...,2026-07-31 12:48:02+00:00,4xkM0BwLM9H2IUcbYzpcBI,77SW9BnxLY8rJ0RciFqkHh,92
26,2RkZ5LkEzeHGRsmDqKwmaJ,Ordinary,186964,https://open.spotify.com/track/2RkZ5LkEzeHGRsm...,2026-07-31 12:48:02+00:00,1eCGY9WJpYgtaFh1Lk2KNo,0fTSzq9jAh4c36UVb4V7CB,81
27,7e4zDInS6tA2jwzphvs2Ay,Jamaican (Bam Bam),156393,https://open.spotify.com/track/7e4zDInS6tA2jwz...,2026-07-31 12:48:02+00:00,5ZX3Zdp20YCGI4ruAfZlMj,"5PlfkPxwCpRRWQJBxCa0By, 0F3tUZeb9dLNEpxCpzEBQt",79
28,1JSTJqkT5qHq8MDJnJbRE1,Every Breath You Take,253920,https://open.spotify.com/track/1JSTJqkT5qHq8MD...,2026-07-31 12:48:02+00:00,5W9OT0a5iZlBr83a9WMKFY,5NGO30tJxFlKixkPSgXcFE,94
29,003vvx7Niy0yvhvHt4a68B,Mr. Brightside,222973,https://open.spotify.com/track/003vvx7Niy0yvhv...,2026-07-31 12:48:02+00:00,4piJq7R3gjUOxnYs6lDCTg,0C0XlULifJtAgn6ZNCW2eu,86
30,4xoY4lZNoTjEuHsSmhgF1G,Sesi Potret,243000,https://open.spotify.com/track/4xoY4lZNoTjEuHs...,2026-07-31 12:48:02+00:00,25hlG9lEbc2ARvZXY4ZDhv,"0agUNq8PH1QSgm88EuhM1u, 3MMDw11m6HJrXlGOE3honc",92
31,5y2ijHECwFYWqcAHKTZgzD,Risk It All,204068,https://open.spotify.com/track/5y2ijHECwFYWqcA...,2026-07-31 12:48:02+00:00,7vI4iTxDmgEN63liQHPEX1,0du5cEVh5yTK9QJze8zA0C,89
32,6dOtVTDdiauQNBQEDOtlAB,BIRDS OF A FEATHER,210373,https://open.spotify.com/track/6dOtVTDdiauQNBQ...,2026-07-31 12:48:02+00:00,7aJuG4TFXa2hmE4z1yxc3n,6qqNVTkY8uBg9cP3Jd7DAH,76
33,2lpygKqzPFtItQ4ss3cgfb,Cinderella (feat. Ty Dolla $ign),480186,https://open.spotify.com/track/2lpygKqzPFtItQ4...,2026-07-31 12:48:02+00:00,6f6tko6NWoH00cyFOl4VYQ,"4LLpKhyESsyAXpc4laK94U, 7c0XG5cIJTrrAgEC3ULPiq",78
34,5Ohxk2dO5COHF1krpoPigN,Sign of the Times,340706,https://open.spotify.com/track/5Ohxk2dO5COHF1k...,2026-07-31 12:48:02+00:00,1FZKIm3JVDCxTchXDo5jOV,6KImCVD70vtIoJWnq6nGn3,94
35,21IYMdzTrzSe191Cy5eMap,Sailor Song,211978,https://open.spotify.com/track/21IYMdzTrzSe191...,2026-07-31 12:48:02+00:00,58vZavXqh1P5uoTXteudWl,1iCnM8foFssWlPRLfAbIwo,83
36,3w3y8KPTfNeOKPiqUTakBh,Locked out of Heaven,233478,https://open.spotify.com/track/3w3y8KPTfNeOKPi...,2026-07-31 12:48:02+00:00,58ufpQsJ1DS5kq4hhzQDiI,0du5cEVh5yTK9QJze8zA0C,90
37,6hpuesKPNa3WhV48O7Fa47,SUPERESTRELLA,183529,https://open.spotify.com/track/6hpuesKPNa3WhV4...,2026-07-31 12:48:02+00:00,1lKquzZlhL5AWMHTeGej4M,7eLcDZDYHXZCebtQmVFL25,95
38,3oTuTpF1F3A7rEC6RKsMRz,Raindance (feat. Tems),219743,https://open.spotify.com/track/3oTuTpF1F3A7rEC...,2026-07-31 12:48:02+00:00,24f1GFXCkViGoRpmGqlSSl,"6Ip8FS7vWT1uKkJSweANQK, 687cZJR45JO7jhk1LHIbgq",77
39,5yvVYFDUpbnjcnRBgjwTzM,Dracula - JENNIE Remix,209720,https://open.spotify.com/track/5yvVYFDUpbnjcnR...,2026-07-31 12:48:02+00:00,6KFq3hJB6JnNvDbEHRvPoK,"5INjqkS1o8h1imAzPqGZBb, 250b0Wlc5Vk0CoUsaCY84M",77
40,514joG57v4yKTsfQmz7stz,Janice STFU,237344,https://open.spotify.com/track/514joG57v4yKTsf...,2026-07-31 12:48:02+00:00,0OAv7DCME2AV4q1KPO95HY,3TVXtAsR1Inumwj472S9r4,84
41,6sGIMrtIzQjdzNndVxe397,So Easy (To Fall In Love),169000,https://open.spotify.com/track/6sGIMrtIzQjdzNn...,2026-07-31 12:48:02+00:00,0l8zYqoUeBYg47Gmevq9HZ,00x1fYSGhdqScXBRpSj3DW,92
42,1rIKgCH4H52lrvDcz50hS8,Lush Life,200646,https://open.spotify.com/track/1rIKgCH4H52lrvD...,2026-07-31 12:48:02+00:00,5YLRVHDVRw3QqWbeTGpC5B,1Xylc3o4UrD53lo9CvFvVg,85
43,70LcF31zb1H0PyJoS1Sx1r,Creep,238640,https://open.spotify.com/track/70LcF31zb1H0PyJ...,2026-07-31 12:48:02+00:00,3gBVdu4a1MMJVMy6vwPEb8,4Z8W4fKeB5YxbusRsdQVPb,85
44,5TFD2bmFKGhoCRbX61nXY5,NUEVAYoL,183685,https://open.spotify.com/track/5TFD2bmFKGhoCRb...,2026-07-31 12:48:02+00:00,5K79FLRUCSysQnVESLcTdb,4q3ewBCX7sLwd24euuV69X,87
45,2lTm559tuIvatlT1u0JYG2,BAILE INoLVIDABLE,367725,https://open.spotify.com/track/2lTm559tuIvatlT...,2026-07-31 12:48:02+00:00,5K79FLRUCSysQnVESLcTdb,4q3ewBCX7sLwd24euuV69X,88
46,3d0WouFnFmr0K3kjeza3fF,Hips Don't Lie (feat. Wyclef Jean),220360,https://open.spotify.com/track/3d0WouFnFmr0K3k...,2026-07-31 12:48:02+00:00,2cHhcN6iNLNXc7FByWBGi5,"0EmeFodog0BfCgMzAIvKQp, 7aBzpmFXB4WWpPl2F7RjBe",87
47,2uXlHCUbq9OMUwx3hrk06o,Riptide,204280,https://open.spotify.com/track/2uXlHCUbq9OMUwx...,2026-07-31 12:48:02+00:00,2biVG6BYnVVSwLYd1OjbPT,10exVja0key0uqUkk6LJRT,89
48,1zi7xx7UVEFkmKfv06H8x0,One Dance,173986,https://open.spotify.com/track/1zi7xx7UVEFkmKf...,2026-07-31 12:48:02+00:00,40GMAhriYJRO1rsY4YdrZb,"3TVXtAsR1Inumwj472S9r4, 3tVQdUvClmAT7URs9V3rsp...",95
49,3C0nOe05EIt1390bVABLyN,On The Floor,284866,https://open.spotify.com/track/3C0nOe05EIt1390...,2026-07-31 12:48:02+00:00,3sysiYphqNRQw7VKLCg1yE,"2DlGxzQSjYe5N6G9nkYghR, 0TnOYISbd1XYRBk9myaseg",90